### PR TITLE
Include the seal when populating the header for a new block

### LINKED ISSUE #11445: [permission] finalizeChange is not called when maximumEmptySteps is set
- **Parity Ethereum version**: 2.7.1 
- **Operating system**:  MacOS 
- **Installation**: docker (from parity repo)
- **Fully synchronized**: -
- **Network**: aura (private)
- **Restarted**: yes

**Actual**

`
2020-02-04 12:46:45 UTC IO Worker #3 INFO engine  Signal for switch to contract-based validator set.
2020-02-04 12:46:45 UTC IO Worker #3 INFO engine  Initial contract validators: [0x662eb278299d1f2069a52d09f308a599a99afd39, 0x59f6566306843fb7d18f782733e19223ca5f07ab, 0xade4279d444bb1183e733dcc1adffa06b53d72d2]
2020-02-04 12:46:45 UTC IO Worker #3 INFO import  Imported #7 0x6d71…8993 (0 txs, 0.00 Mgas, 3 ms, 1.30 KiB)
2020-02-04 12:47:08 UTC IO Worker #1 INFO import     2/25 peers     19 KiB chain   28 KiB db  0 bytes queue    3 KiB sync  RPC:  0 conn,    1 req/s,  112 µs
2020-02-04 12:47:38 UTC IO Worker #1 INFO import     2/25 peers     19 KiB chain   28 KiB db  0 bytes queue    3 KiB sync  RPC:  0 conn,    5 req/s,   69 µs
2020-02-04 12:48:08 UTC IO Worker #3 INFO import     2/25 peers     19 KiB chain   28 KiB db  0 bytes queue    3 KiB sync  RPC:  0 conn,    4 req/s,  108 µs
2020-02-04 12:48:38 UTC IO Worker #2 INFO import     2/25 peers     19 KiB chain   28 KiB db  0 bytes queue    3 KiB sync  RPC:  0 conn,    4 req/s,  107 µs
2020-02-04 12:49:08 UTC IO Worker #2 INFO import     2/25 peers     19 KiB chain   28 KiB db  0 bytes queue    3 KiB sync  RPC:  0 conn,    1 req/s,  145 µs
2020-02-04 12:49:30 UTC IO Worker #0 INFO import  Imported #8 0xad09…1e07 (0 txs, 0.00 Mgas, 0 ms, 1.30 KiB)
`

**Expected**
`
2020-02-04 12:55:40 UTC Verifier #1 INFO engine  Signal for switch to contract-based validator set.
2020-02-04 12:55:40 UTC Verifier #1 INFO engine  Initial contract validators: [0x662eb278299d1f2069a52d09f308a599a99afd39, 0x59f6566306843fb7d18f782733e19223ca5f07ab, 0xade4279d444bb1183e733dcc1adffa06b53d72d2]
2020-02-04 12:55:40 UTC Verifier #1 INFO import  Imported #7 0x2040…c1b6 (0 txs, 0.00 Mgas, 1 ms, 0.57 KiB)
2020-02-04 12:55:45 UTC IO Worker #0 INFO engine  Applying validator set change signalled at block 7
2020-02-04 12:55:45 UTC IO Worker #0 INFO import  Imported #8 0xa4a4…609b (0 txs, 0.00 Mgas, 6 ms, 0.57 KiB)
`

**Step to Reproduce**

> genesis

        "name":"parity",
        "engine": {
           "authorityRound": {
              "params": {
                "stepDuration": "5",
                "validators" : {
                    "multi": {
                        "0": {
                            "list": [ "0x662eb278299d1f2069a52d09f308a599a99afd39", "0x59f6566306843fb7d18f782733e19223ca5f07ab", "0xade4279d444bb1183e733dcc1adffa06b53d72d2" ]
                        },
                        "7": {
                            "contract" : "0x289631594ec63a592aed277Ef6Dce46937959A7e"
                        }
                    }
                },
                "blockReward": "10",
                "emptyStepsTransition" : "5",
	            "maximumEmptySteps": "10"
            }
        }
    

If `maximumEmptySteps` parameter is removed, message ` Applying validator set change signalled at block 7` will be appeared on log output.

If I set `emptyStepsTransition` higher than block number of validator contract supposed to activate, then `finalizeChange` is successfully called and message `Applying validator set change signalled at block 7` will be present. But once block number reach  `emptyStepsTransition`, any method that should trigger `finalizeChange` called (i.e. `addValidator`) will not trigger  `finalizeChange` properly

### PR DESCRIPTION
**Pull request by dvdplm**
Include the seal when populating the header for a new block so that the state root is calculated properly.

The issue here is that when `emptyStepTransition` and `maximumEmptySteps` are both set in the chain spec there are verification errors on block import, at [Stage 5](https://github.com/paritytech/parity-ethereum/blob/99271db9d3b5afb13ca2863a4fcad34a47adc489/ethcore/verification/src/verification.rs#L242).
A block is issued by a node and the other nodes can't verify it: state root mismatch.
Now, the Seal fields contain `EmptySteps` after the transition and each empty step implies a reward for the validator that emitted the empty step. This means that the accounts involved get touched, so the state root changes. Before that last step of the verification we call `check_and_lock_block()` in [`client.rs`](https://github.com/paritytech/parity-ethereum/blob/654632264b81e0dbeffdbafbc96cfa4273f43a87/ethcore/src/client/client.rs#L311) which calls `enact_verified()` which calls `enact()`.
[`enact()`](https://github.com/paritytech/parity-ethereum/blob/77643c13e80ca09d9a6b10631034f5a1568ba6d3/ethcore/src/block.rs#L406) essentially [copies over data from the incoming block header](https://github.com/paritytech/parity-ethereum/blob/77643c13e80ca09d9a6b10631034f5a1568ba6d3/ethcore/src/block.rs#L448-L453) (the one with the Seal with the EmptySteps) but before this PR it does not copy over the seal from the block being imported to the newly prepared `LockedBlock`.
The rewards are bestowed in [`on_close_block()`](https://github.com/paritytech/parity-ethereum/blob/2c4b51c3ea301711eda8c04168e484043d4e17e6/ethcore/engines/authority-round/src/lib.rs#L1559-L1562) and then the state is committed (which sets the state root).
I think this is what is going on. I didn't use `LockedBlock::seal()` because it returns a `SealedBlock` and I wasn't sure if we should change the return type tbh.

Fixes #11445

### CODE REVIEW

File: ethcore/src/block.rs [hunk 1]
```diff
@@ -222,6 +222,7 @@ impl<'x> OpenBlock<'x> {
 		self.block.header.set_timestamp(header.timestamp());
 		self.block.header.set_uncles_hash(*header.uncles_hash());
 		self.block.header.set_transactions_root(*header.transactions_root());
+		self.block.header.set_seal(header.seal().to_vec());
```
Comment (dvdplm) [inline ethcore/src/block.rs]: The fix for #11445 is here: without this the `LockedBlock` built by `enact()` lacks the seal and this causes the state root to be wrong.

File: ethcore/engines/authority-round/src/lib.rs [hunk 2]
```diff
@@ -720,17 +720,22 @@ fn header_signature(header: &Header, empty_steps_transition: u64) -> Result<Sign
 	.as_val::<H520>().map(Into::into)
 }
 
-// extracts the raw empty steps vec from the header seal. should only be called when there are 3 fields in the seal
-// (i.e. header.number() >= self.empty_steps_transition)
-fn header_empty_steps_raw(header: &Header) -> &[u8] {
-	header.seal().get(2).expect("was checked with verify_block_basic; has 3 fields; qed")
+// Extracts the empty steps from the header seal. Returns data only when there are 3 fields in the seal
```
Comment (tomusdrw) [inline ethcore/engines/authority-round/src/lib.rs]: Why remove `raw` from the docs? Do you think it's redundant since the method name (and types) indicate it's raw?

File: ethcore/src/block.rs (hunk 1 above)
Comment (tomusdrw) [reply ethcore/src/block.rs]: This doesn't seem right for me though. The idea with block types is that you go from:
`OpenBlock -> ClosedBlock -> LockedBlock -> SealedBlock`
and only the last type is guaranteed to have the seal.

How come the `seal` is included in the state root anyway? It's two separate things and really I don't see a way how `seal` affects the `state`?

**Comment by tomusdrw** [comment]
Oh, apologies. I just read the description and now I understand how `seal` can affect `state` via block rewards. I think it's a good idea to add this as a documentation for seal copying line in `populate_from`

File: ethcore/engines/authority-round/src/lib.rs (hunk 2 above)
Comment (dvdplm) [reply ethcore/engines/authority-round/src/lib.rs]: I removed it because I didn't think "raw" made sense here. In what sense are the steps "raw"? Maybe it should be "Extracts the RLP of the empty steps from the header seal. …"?

Comment (tomusdrw) [reply ethcore/engines/authority-round/src/lib.rs]: `s/raw/RLP bytes/` makes sense!

File: ethcore/src/block.rs (hunk 1 above)
Comment (dvdplm) [reply ethcore/src/block.rs]: Added comment + ref to this PR. It still feels a bit dirty to do this here and I'm open to alternatives.

Comment (niklasad1) [reply ethcore/src/block.rs]: question: is this not called from `Miner::seal_and_import_block_internally` code path? It seems like `Miner::prepare_block` doesn't call `OpenBlock::new`, correct?

Comment (dvdplm) [reply ethcore/src/block.rs]: Not sure I understand what you mean, but the reverse call-graph for `populate_from()` looks like this:

```
populate_from() is called by…
	enact() is called by…
		enact_verified() is called by…
			check_and_lock_block() is called by…
				import_verified_blocks() is called by… (in impl Importer)
					import_verified_blocks() is called by… (in impl ImportBlock for Client)
						message() is called by… (ClientIoMessage::BlockVerified)
						flush_queue()
```

In other words, `populate_from()` is only called on the block verification path, not for block producing.

Comment (niklasad1) [reply ethcore/src/block.rs]: cool, yeah that's what I meant.

File: ethcore/engines/authority-round/src/lib.rs [hunk 3]
```diff
@@ -720,17 +720,22 @@ fn header_signature(header: &Header, empty_steps_transition: u64) -> Result<Sign
...
 }
 
-// extracts the raw empty steps vec from the header seal. should only be called when there are 3 fields in the seal
-// (i.e. header.number() >= self.empty_steps_transition)
-fn header_empty_steps_raw(header: &Header) -> &[u8] {
-	header.seal().get(2).expect("was checked with verify_block_basic; has 3 fields; qed")
+// Extracts the RLP bytes of the empty steps from the header seal. Returns data only when there are
+// 3 fields in the seal. (i.e. header.number() >= self.empty_steps_transition).
+fn header_empty_steps_raw(header: &Header) -> Option<&[u8]> {
+	header.seal().get(2).map(Vec::as_slice )
```
Comment (andresilva) [inline ethcore/engines/authority-round/src/lib.rs]:
```suggestion
	header.seal().get(2).map(Vec::as_slice)
```

File: ethcore/engines/authority-round/src/lib.rs [hunk 4]
```diff
@@ -970,11 +975,15 @@ impl AuthorityRound {
 	/// Drops all `EmptySteps` less than or equal to the passed `step`, irregardless of the parent hash.
 	fn clear_empty_steps(&self, step: u64) {
 		let mut empty_steps = self.empty_steps.lock();
-		*empty_steps = empty_steps.split_off(&EmptyStep {
+		if empty_steps.is_empty() {
+			return
```
Comment (andresilva) [inline ethcore/engines/authority-round/src/lib.rs]:
```suggestion
			return;
```

Super nit, just personal preference but I prefer statements (rather than expressions) to always end with `;`.

File: ethcore/src/block.rs [hunk 5]
```diff
@@ -222,6 +222,10 @@ impl<'x> OpenBlock<'x> {
 		self.block.header.set_timestamp(header.timestamp());
 		self.block.header.set_uncles_hash(*header.uncles_hash());
 		self.block.header.set_transactions_root(*header.transactions_root());
+		// For Aura-based chains, the seal may contain EmptySteps which are used to bestow awards;
```
Comment (andresilva) [inline ethcore/src/block.rs]:
```suggestion
		// For Aura-based chains, the seal may contain EmptySteps which are used to bestow rewards;
```

**Comment by dvdplm** [comment]
> what I don't know is if this issue was always there or if it surfaced due to some recent change. I believe it must be the later because I tested the empty steps feature when I implemented it, and as it stands (before this PR) it is impossible to use it.

Yeah, that's my biggest concern too: it must have been broken for quite while. I guess it's possible that users run old versions and haven't run into this yet.

**Comment by niklasad1** [comment]
> Yeah, that's my biggest concern too: it must have been broken for quite while. I guess it's possible that users run old versions and haven't run into this yet.

I still suspect this `Clique engine` PR but I might be wrong :)
