### PR TITLE
Reset blockchain properly

### LINKED ISSUE #10665: Stage 4 block verification failed on startup
- **Parity Ethereum version**: 2.4.6
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: yes
- **Network**: kovan
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

After docker restarting parity fails to start sync

```
2019-05-15 12:55:39 UTC Starting Parity-Ethereum/v2.4.6-stable-94164e1-20190514/x86_64-linux-gnu/rustc1.34.1
2019-05-15 12:55:39 UTC Keys path /home/parity/.local/share/io.parity.ethereum//keys/kovan
2019-05-15 12:55:39 UTC DB path /home/parity/.local/share/io.parity.ethereum//chains/kovan/db/9bf388941c25ea98
2019-05-15 12:55:39 UTC State DB configuration: archive +Fat +Trace
2019-05-15 12:55:39 UTC Operating mode: active
2019-05-15 12:55:39 UTC Warning: Warp Sync is disabled because Fat DB is turned on.
2019-05-15 12:55:39 UTC Configured for Kovan Testnet using AuthorityRound engine
2019-05-15 12:55:39 UTC Listening for new connections on 0.0.0.0:8546.
2019-05-15 12:55:39 UTC Accepted a new tcp connection from 10.136.10.94:57239.
2019-05-15 12:55:40 UTC Stage 4 block verification failed for #10960441 (0xc204…f245)
Error: Error(Engine(NotProposer(Mismatch { expected: 0x00e6d2b931f55a3f1701c7389d592a7778897879, found: 0x00d6cc1ba9cf89bd2e58009741f4f7325badc0ed })), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0:     0x56194353f19d - <no info>
   1:     0x56194353e562 - <no info>
   2:     0x561943297ec8 - <no info>
   3:     0x5619432981f5 - <no info>
   4:     0x561942d5ff63 - <no info>
   5:     0x561942d695b7 - <no info>
   6:     0x561942b6e2ed - <no info>
   7:     0x561942d38ee9 - <no info>
   8:     0x5619425c82c0 - <no info>
   9:     0x561942bf97b9 - <no info>
  10:     0x561942bc3e88 - <no info>
  11:     0x561942bc610c - <no info>
  12:     0x561942bf3f9a - <no info>
  13:     0x561942ce2ddd - <no info>
  14:     0x5619435b7ed9 - <no info>
  15:     0x561942c45b4e - <no info>
  16:     0x5619435b721d - <no info>
  17:     0x7fe720cb76b9 - <no info>
  18:     0x7fe7207d741c - <no info>
  19:                0x0 - <no info>) } })
2019-05-15 12:55:40 UTC
Bad block detected: Error(Engine(NotProposer(Mismatch { expected: 0x00e6d2b931f55a3f1701c7389d592a7778897879, found: 0x00d6cc1ba9cf89bd2e58009741f4f7325badc0ed })), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0:     0x56194353f19d - <no info>
   1:     0x56194353e562 - <no info>
   2:     0x561943297ec8 - <no info>
   3:     0x5619432981f5 - <no info>
   4:     0x561942d5ff63 - <no info>
   5:     0x561942d695b7 - <no info>
   6:     0x561942b6e2ed - <no info>
   7:     0x561942d38ee9 - <no info>
   8:     0x5619425c82c0 - <no info>
   9:     0x561942bf97b9 - <no info>
  10:     0x561942bc3e88 - <no info>
  11:     0x561942bc610c - <no info>
  12:     0x561942bf3f9a - <no info>
  13:     0x561942ce2ddd - <no info>
  14:     0x5619435b7ed9 - <no info>
  15:     0x561942c45b4e - <no info>
  16:     0x5619435b721d - <no info>
  17:     0x7fe720cb76b9 - <no info>
  18:     0x7fe7207d741c - <no info>
  19:                0x0 - <no info>) } })
RLP: f902f6f90246a0159c1fecf41d5356618ec2286d92dbb5b3b53c5aec7902509566b14a89903752a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d493479400d6cc1ba9cf89bd2e58009741f4f7325badc0eda0380bc8466f8add1fc935f865f1dd3d5c5e61a81e12c4a24e9d063ec6a692c08ba0d7e3c695873522c7497e60b38f74a132a89fa3a24e4c2a0536ba453412a1587ca0dc7f95c926a4a85e02a1a05490518ef4ef1088f69018e3509f2fc21d8195a887b901000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000080000000000000000000040000000000000000000000000040000000000800000000000000000000000000000000000000000000002000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000001000000000000000000000000001020000000000000000000000000000000000000000000000000000000000090fffffffffffffffffffffffffffffffd83a73e39837a120082b12b845cdbfa009fde830204068f5061726974792d457468657265756d86312e33342e31827769841736fe80b8419d047d9284b516c58e1afd154d77d9830475963b9eafcd12c16fb1edc026664d248dd24e7bd0e7c98d89ec086b0efdbcbcaa93f3e3fece06f669bc19a7dfe8bc01f8aaf8a8228471489bb382e651945a7353e9ad230dc2ac685f4dab091fd2b2d2a77e80b844095ea7b300000000000000000000000083096801cfb66db85024520ca5b3af136311a34600000000000000000000000000000000000000000000000000000000000003e81ca0619bece788d97020b1566ecedf358bf2af26c001ed20616de5015ab5f26cf87fa020de68e31bf592e742122330e617b896d7b82c95401afe1d15df8fc81cdb7ad0c0
Header: Header { parent_hash: 0x159c1fecf41d5356618ec2286d92dbb5b3b53c5aec7902509566b14a89903752, timestamp: 1557920256, number: 10960441, author: 0x00d6cc1ba9cf89bd2e58009741f4f7325badc0ed, transactions_root: 0xd7e3c695873522c7497e60b38f74a132a89fa3a24e4c2a0536ba453412a1587c, uncles_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, extra_data: [222, 131, 2, 4, 6, 143, 80, 97, 114, 105, 116, 121, 45, 69, 116, 104, 101, 114, 101, 117, 109, 134, 49, 46, 51, 52, 46, 49, 130, 119, 105], state_root: 0x380bc8466f8add1fc935f865f1dd3d5c5e61a81e12c4a24e9d063ec6a692c08b, receipts_root: 0xdc7f95c926a4a85e02a1a05490518ef4ef1088f69018e3509f2fc21d8195a887, log_bloom: 0x00000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000800000000000000000000400000000000000000000000000400000000008000000000000000000000000000000000000000000000020000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000010200000000000000000000000000000000000000000000000000000000000, gas_used: 45355, gas_limit: 8000000, difficulty: 340282366920938463463374607431768211453, seal: [[132, 23, 54, 254, 128], [184, 65, 157, 4, 125, 146, 132, 181, 22, 197, 142, 26, 253, 21, 77, 119, 217, 131, 4, 117, 150, 59, 158, 175, 205, 18, 193, 111, 177, 237, 192, 38, 102, 77, 36, 141, 210, 78, 123, 208, 231, 201, 141, 137, 236, 8, 107, 14, 253, 188, 188, 170, 147, 243, 227, 254, 206, 6, 246, 105, 188, 25, 167, 223, 232, 188, 1]], hash: Some(0xc204c637aaeae7fd2fa9034dacaf35d5f290bf5ba35fb8adcf49a7748e7ef245) }
Uncles:
Transactions:[Tx 0] UnverifiedTransaction { unsigned: Transaction { nonce: 34, gas_price: 1900583859, gas: 58961, action: Call(0x5a7353e9ad230dc2ac685f4dab091fd2b2d2a77e), value: 0, data: [9, 94, 167, 179, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 131, 9, 104, 1, 207, 182, 109, 184, 80, 36, 82, 12, 165, 179, 175, 19, 99, 17, 163, 70, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 232] }, v: 28, r: 44149842661914932399584453173009786420610147425525440546403923820432287660159, s: 14866975107517740504714974888260480849283556163795478444115221606568434563792, hash: 0x19b18ab00b67672f28314f4de43fc43a8bc8cf9d1fcc298ecaf48fb9532091c1 }
2019-05-15 12:55:44 UTC Public node URL: enode://1d3357c77f61f782d98a3d52daca8e6588df427ad898b56c597b1adbdcfae19c1275b3672e4af88e5c56a05bab68783fe4e8b5b000f3f1e6437661221d136920@172.18.0.2:30303
2019-05-15 12:56:14 UTC    3/25 peers    270 KiB chain   14 KiB db  0 bytes queue  260 KiB sync  RPC:  1 conn,    1 req/s,  250 µs
```

Is there any option to fix it without full resync?

### PR DESCRIPTION
**Pull request by seunlanlege**
Previously the reset blockchain feature wrongly assumed that the block hashes were the keys for `BlockDetails` in COL_EXTRA that has been corrected.
Also, there was a known issue with the reset feature where deleted blocks wouldn't be imported again because they were a "known child" of an existing block
that has also been corrected.

Should fix #10665

### CODE REVIEW

File: ethcore/src/client/client.rs [hunk 1]
```diff
@@ -1338,27 +1338,41 @@ impl BlockChainReset for Client {
 		for hash in &blocks_to_delete {
 			db_transaction.delete(::db::COL_HEADERS, &hash.hash());
 			db_transaction.delete(::db::COL_BODIES, &hash.hash());
-			db_transaction.delete(::db::COL_EXTRA, &hash.hash());
+			Writable::delete::<BlockDetails, H264>(&mut db_transaction, ::db::COL_EXTRA, &hash.hash());
```
Comment (ordian) [inline ethcore/src/client/client.rs]: Shouldn't it be `Writable::delete::<H264, BlockDetails>`, no?

Comment (seunlanlege) [reply ethcore/src/client/client.rs]: That's not how, the `Key` trait works, yeah, it confused me too.

https://github.com/paritytech/parity-ethereum/blob/7c335e87642b848f61ab3ee7bbff5964b53d6f11/ethcore/db/src/db.rs#L95-L98

https://github.com/paritytech/parity-ethereum/blob/7c335e87642b848f61ab3ee7bbff5964b53d6f11/ethcore/db/src/keys.rs#L82-L88

https://github.com/paritytech/parity-ethereum/blob/7c335e87642b848f61ab3ee7bbff5964b53d6f11/ethcore/db/src/db.rs#L83-L89

File: ethcore/src/client/client.rs [hunk 2]
```diff
@@ -1338,27 +1338,41 @@ impl BlockChainReset for Client {
...
 			Writable::delete::<H256, BlockNumberKey>
 				(&mut db_transaction, ::db::COL_EXTRA, &hash.number());
 		}
 
+		let last_hash = blocks_to_delete.last().expect("blocks_to_delete isn't empty; qed").hash();
```
Comment (tomusdrw) [inline ethcore/src/client/client.rs]: That doesn't sound like a proof, why is it non empty?

File: ethcore/src/client/client.rs [hunk 3]
```diff
@@ -1338,27 +1338,41 @@ impl BlockChainReset for Client {
...
+		let mut best_block_details = Readable::read::<BlockDetails, H264>(
+			&**self.db.read().key_value(),
+			::db::COL_EXTRA,
+			&best_block_hash
+		).expect("best_block_details should exist; qed");
```
Comment (tomusdrw) [inline ethcore/src/client/client.rs]: ditto

**Comment by seunlanlege** [comment]
@tomusdrw 

please could you look at this again?

File: ethcore/blockchain/src/blockchain.rs [hunk 4]
```diff
@@ -869,6 +854,14 @@ impl BlockChain {
 		}
 	}
 
+	/// clears all caches for testing purposes
+	pub fn clear_cache(&self) {
```
Comment (ordian) [inline ethcore/blockchain/src/blockchain.rs]: if it's only used in tests, then put it behind `#[cfg(test)]` attribute

File: ethcore/src/client/client.rs [hunk 5]
```diff
@@ -1327,37 +1327,62 @@ impl BlockChainReset for Client {
...
+		let mut best_block_details = Readable::read::<BlockDetails, H264>(
+			&**self.db.read().key_value(),
+			::db::COL_EXTRA,
+			&*best_block_hash
+		).ok_or("block was previously imported; best_block_details should exist; qed")?;
+
+		let (_, last_hash) = blocks_to_delete.last()
+			.ok_or("num is > 0; blocks can't be empty; qed")?;
+		// remove the last block as a child so that it can be re-imported
+		// ethcore/blockchain/src/blockchain.rs:667
```
Comment (ordian) [inline ethcore/src/client/client.rs]: it's better to refer by a function name, since line numbers can change

File: ethcore/src/client/client.rs [hunk 6]
```diff
@@ -1327,37 +1327,62 @@ impl BlockChainReset for Client {
...
 
-		let mut db_transaction = DBTransaction::with_capacity((num + 1) as usize);
-
-		for hash in &blocks_to_delete {
-			db_transaction.delete(::db::COL_HEADERS, &hash.hash());
-			db_transaction.delete(::db::COL_BODIES, &hash.hash());
-			db_transaction.delete(::db::COL_EXTRA, &hash.hash());
-			Writable::delete::<H256, BlockNumberKey>
-				(&mut db_transaction, ::db::COL_EXTRA, &hash.number());
+		for _ in 0..=num {
```
Comment (ordian) [inline ethcore/src/client/client.rs]: this was previously `num`, not `=num`, could you elaborate why?

File: ethcore/src/client/client.rs [hunk 7]
```diff
@@ -1327,37 +1327,62 @@ impl BlockChainReset for Client {
...
+			Writable::delete::<BlockDetails, H264>(&mut db_transaction, ::db::COL_EXTRA, &*hash);
+			Writable::delete::<H256, BlockNumberKey>
+				(&mut db_transaction, ::db::COL_EXTRA, &*number);
+		}
+
+		let mut best_block_details = Readable::read::<BlockDetails, H264>(
+			&**self.db.read().key_value(),
+			::db::COL_EXTRA,
+			&*best_block_hash
+		).ok_or("block was previously imported; best_block_details should exist; qed")?;
```
Comment (ordian) [inline ethcore/src/client/client.rs]: can this block be removed in the meantime?

Comment (seunlanlege) [reply ethcore/src/client/client.rs]: don't understand the question.

File: ethcore/src/client/client.rs (hunk 6 above)
Comment (tomusdrw) [reply ethcore/src/client/client.rs]: Yeah, seems that we might remove too much, no? If I want to remove `num=1` block it should only add `best_block_hash` to the list of blocks to delete, so the loop should spin only once.

File: ethcore/src/client/client.rs [hunk 8]
```diff
@@ -1327,37 +1327,62 @@ impl BlockChainReset for Client {
...
+		let hashes = blocks_to_delete.iter().map(|(_, hash)| hash).collect::<Vec<_>>();
+		info!("Deleting block hashes {}",
+			  Colour::Red
+				  .bold()
+				  .paint(format!("{:#?}", hashes))
+		);
+
+		let mut db_transaction = DBTransaction::with_capacity(blocks_to_delete.len());
+		let (_, best_block_hash) = blocks_to_delete.first()
+			.ok_or("num is > 0; blocks can't be empty; qed")?;
```
Comment (tomusdrw) [inline ethcore/src/client/client.rs]: since you're providing a proof that could be `expect`

File: ethcore/src/client/client.rs (hunk 7 above)
Comment (tomusdrw) [reply ethcore/src/client/client.rs]: We do schedule it for deletion in `db_transaction` above, but it''s not yet comitted, so the block indeed should be there.
However this is an `Err` not expect, so a proof is not even needed in that case.

Comment (ordian) [reply ethcore/src/client/client.rs]: Sorry I meant if the block could be deleted from a separate thread/process. Looks like in this case we're using rocksdb, which doesn't allow read/write from multiple processes and this method is only used in cli, so this is the only thread doing mutation, right? But if change our db backend to lmdb, this is something to keep in mind.

**Comment by ordian** [comment]
to fix cargo audit, merge with master

File: ethcore/blockchain/src/blockchain.rs (hunk 4 above)
Comment (ordian) [reply ethcore/blockchain/src/blockchain.rs]: Looks like it's not possible, this attribute doesn't work across crates (blockchain is a separate crate).

File: ethcore/src/client/client.rs (hunk 6 above)
Comment (seunlanlege) [reply ethcore/src/client/client.rs]: ok so during testing best_block + num - 1 block wasn't being reset.

I later figured out that the test client adds a genesis block. so reverted it

File: ethcore/src/client/client.rs [hunk 9]
```diff
@@ -1327,37 +1327,60 @@ impl BlockChainReset for Client {
...
+		} else if num == 0 {
+			return Err("invalid number of blocks to reset".into())
 		}
 
-		let (blocks_to_delete, best_block_hash) = self.chain.read()
-			.block_headers_from_best_block(num)
-			.ok_or("Attempted to reset past genesis block")?;
+		let mut blocks_to_delete = Vec::with_capacity(num as usize);
+		let mut best_block_hash = self.chain.read().best_block_hash();
+		let mut batch = DBTransaction::with_capacity(blocks_to_delete.len());
```
Comment (seunlanlege) [inline ethcore/src/client/client.rs]: damn, this should've been `DBTransaction::with_capacity(blocks_to_delete.capacity())`, shouldn't be much of a problem. this code runs in cli so the cost of resizing the buffer is negligible.

**Comment by CremaFR** [comment]
It seems v2.4.7-stable does not include the fix. 
v2.5.2-beta has it and reset blocks properly
