### PR TITLE
SecretStore: use in-memory transport in cluster tests

### LINKED ISSUE #9635: key_server_cluster randomly failing
job: https://gitlab.parity.io/parity/parity-ethereum/-/jobs/100432

pr: #9633 

```
---- key_server_cluster::cluster::tests::ecdsa_signing_session_completes_if_node_does_not_have_a_share stdout ----
thread 'key_server_cluster::cluster::tests::ecdsa_signing_session_completes_if_node_does_not_have_a_share' panicked at 'no result in 300ms', secret_store/src/key_server_cluster/cluster.rs:1253:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   7: ethcore_secretstore::key_server_cluster::cluster::tests::ecdsa_signing_session_completes_if_node_does_not_have_a_share
   8: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:642
   9: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
```

job: https://gitlab.parity.io/parity/parity-ethereum/-/jobs/100420

pr: #9360

```
---- key_server_cluster::cluster::tests::schnorr_signing_session_completes_if_node_does_not_have_a_share stdout ----
thread 'key_server_cluster::cluster::tests::schnorr_signing_session_completes_if_node_does_not_have_a_share' panicked at 'no result in 300ms', secret_store/src/key_server_cluster/cluster.rs:1253:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   7: ethcore_secretstore::key_server_cluster::cluster::tests::schnorr_signing_session_completes_if_node_does_not_have_a_share
   8: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:642
   9: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105

---- key_server_cluster::cluster::tests::ecdsa_signing_session_completes_if_node_does_not_have_a_share stdout ----
thread 'key_server_cluster::cluster::tests::ecdsa_signing_session_completes_if_node_does_not_have_a_share' panicked at 'no result in 300ms', secret_store/src/key_server_cluster/cluster.rs:1253:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   7: ethcore_secretstore::key_server_cluster::cluster::tests::ecdsa_signing_session_completes_if_node_does_not_have_a_share
   8: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:642
   9: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
```

### PR DESCRIPTION
**Pull request by svyatonik**
closes #9635 (at least if my assumption that it has been caused by timeout is true)

This PR doesn't introduces any new functionality, though it has some (non-negligible) non-test code modifications. These are mostly about splitting huge `cluster.rs` into several files:
- `cluster_connections.rs` - contains trait for connections used by cluster + test implementation of these traits;
- `cluster_connections_net.rs` - network implementation of connection traits. This isn't a new code - it is moved from the `cluster.rs`;
`cluster_message_processor.rs` - entity that connects cluster connections with cluster sessions.

Test-related notes:
1) all tests from in `cluster.rs` are now using in-memory connections implementation => no timeouts;
2) there's still single place where timeouts are used - 1000ms when network connections are established in `key_server.rs` tests. I thought about switching to in-memory connections there too, but decided to leave as-is at least for now (until writing proper tests for net-connections). So treat these like integration tests for now. Also - iirc this timeout has never failed - 1s is enough for establishing network connections;
3) most of changes in  tests from `cluster.rs` and various `*_session.rs` are about switching to the new `MessagesLoop` from `cluster.rs` (this removes a lot of duplicate && boilerplate code). It isn't finished yet (there are more `*_session.rs`), but enough for first PR.

### CODE REVIEW

File: secret_store/src/key_server.rs [hunk 1]
```diff
@@ -176,23 +176,26 @@ impl MessageSigner for KeyServerImpl {
 
 impl KeyServerCore {
 	pub fn new(config: &ClusterConfiguration, key_server_set: Arc<KeyServerSet>, self_key_pair: Arc<NodeKeyPair>, acl_storage: Arc<AclStorage>, key_storage: Arc<KeyStorage>) -> Result<Self, Error> {
-		let config = NetClusterConfiguration {
-			threads: config.threads,
+		let threads = config.threads;
+		let cconfig = NetClusterConfiguration {
```
Comment (niklasad1) [inline secret_store/src/key_server.rs]: consider renaming this to `cluster_config`

File: secret_store/src/key_server.rs [hunk 2]
```diff
@@ -460,7 +463,7 @@ pub mod tests {
 	#[test]
 	fn decryption_session_is_delegated_when_node_does_not_have_key_share() {
 		//::logger::init_log();
```
Comment (niklasad1) [inline secret_store/src/key_server.rs]: Not related to this PR, however this logger/comment should be enabled or remove IMHO

File: secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs [hunk 3]
```diff
@@ -1045,148 +1045,205 @@ fn check_nodes_set(all_nodes_set: &BTreeSet<NodeId>, new_nodes_set: &BTreeSet<No
...
+			admin_public: Public,
+			all_nodes_set: BTreeSet<NodeId>,
+			ml: &MessagesLoop,
+			idx: usize
+		) -> S;
 	}
 
-	struct MessageLoop {
+	pub struct MessageLoop<S> {
+		pub ml: MessagesLoop,
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs]: hrm, am I reading this correctly: is every MessageLoop instance containing another MessageLoop?

File: secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs [hunk 4]
```diff
@@ -1045,148 +1045,205 @@ fn check_nodes_set(all_nodes_set: &BTreeSet<NodeId>, new_nodes_set: &BTreeSet<No
...
+		const SIGN_NEW_NODES: bool = true;
+
+		fn create(
+			mut meta: ShareChangeSessionMeta,
+			admin_public: Public,
+			all_nodes_set: BTreeSet<NodeId>,
+			ml: &MessagesLoop,
+			idx: usize
+		) -> SessionImpl {
+			meta.self_node_id = ml.node_key_pair(idx).public().clone();
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs]: clone on `Copy type`

```suggestion
			meta.self_node_id = *ml.node_key_pair(idx).public();
```

File: secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs [hunk 5]
```diff
@@ -1045,148 +1045,205 @@ fn check_nodes_set(all_nodes_set: &BTreeSet<NodeId>, new_nodes_set: &BTreeSet<No
...
 			// generate admin key pair
 			let admin_key_pair = Random.generate().unwrap();
 			let admin_public = admin_key_pair.public().clone();
 
-			// compute original secret key
-			let original_key_pair = original_key_pair.unwrap_or_else(|| gml.compute_key_pair(1));
-
 			// all active nodes set
-			let mut all_nodes_set: BTreeSet<_> = gml.nodes.keys()
+			let mut all_nodes_set: BTreeSet<_> = ml.nodes().iter()
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs]:
```suggestion
			let mut all_nodes_set: BTreeSet<_> = ml.nodes().into_iter()
				.filter(|n| !isolated_nodes_ids.contains(n))
				.collect();

```

File: secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs [hunk 6]
```diff
@@ -1045,148 +1045,205 @@ fn check_nodes_set(all_nodes_set: &BTreeSet<NodeId>, new_nodes_set: &BTreeSet<No
...
 				.filter(|n| !isolated_nodes_ids.contains(n))
 				.cloned()
 				.collect();
 			// new nodes set includes all old nodes, except nodes being removed + all nodes being added
 			let new_nodes_set: BTreeSet<NodeId> = all_nodes_set.iter().cloned()
-				.chain(new_nodes_ids.iter().cloned())
+				.chain(add.iter().map(|kp| kp.public().clone()))
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs]:
```suggestion
				.chain(add.iter().map(|kp| *kp.public()))
```

File: secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs [hunk 7]
```diff
@@ -1045,148 +1045,205 @@ fn check_nodes_set(all_nodes_set: &BTreeSet<NodeId>, new_nodes_set: &BTreeSet<No
...
 				.filter(|n| !removed_nodes_ids.contains(n))
 				.collect();
-			all_nodes_set.extend(new_nodes_ids.iter().cloned());
+			let mut old_set_to_sign = all_nodes_set.clone();
+			all_nodes_set.extend(add.iter().map(|kp| kp.public().clone()));
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs]:
```suggestion
			all_nodes_set.extend(add.iter().map(|kp| *kp.public()));
```

File: secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs [hunk 8]
```diff
@@ -1045,148 +1045,205 @@ fn check_nodes_set(all_nodes_set: &BTreeSet<NodeId>, new_nodes_set: &BTreeSet<No
...
+			if C::SIGN_NEW_NODES {
+				old_set_to_sign.extend(add.iter().map(|kp| kp.public().clone()));
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs]:
```suggestion
				old_set_to_sign.extend(add.iter().map(|kp| *kp.public()));
```

File: secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs [hunk 9]
```diff
@@ -1045,148 +1045,205 @@ fn check_nodes_set(all_nodes_set: &BTreeSet<NodeId>, new_nodes_set: &BTreeSet<No
...
+			}
 			for isolated_node_id in &isolated_nodes_ids {
 				all_nodes_set.remove(isolated_node_id);
 			}
 
 			let meta = ShareChangeSessionMeta {
-				self_node_id: master_node_id.clone(),
-				master_node_id: master_node_id.clone(),
+				self_node_id: master.clone(),
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs]: NodeID is Copy
```suggestion
				self_node_id: master,
```

File: secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs [hunk 10]
```diff
@@ -1045,148 +1045,205 @@ fn check_nodes_set(all_nodes_set: &BTreeSet<NodeId>, new_nodes_set: &BTreeSet<No
...
 			}
+			// isolate nodes from the cluster
+			for isolated_node_id in &isolated_nodes_ids {
+				let idx = ml.nodes().iter().position(|n| n == isolated_node_id).unwrap();
+				ml.exclude(idx);
+			}
+
+			// prepare set of nodes
+			let sessions: BTreeMap<_, _> = (0..ml.nodes().len())
+				.map(|idx| (ml.node(idx), C::create(meta.clone(), admin_public.clone(), all_nodes_set.clone(), &ml, idx)))
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs]:
```suggestion
				.map(|idx| (ml.node(idx), C::create(meta.clone(), admin_public, all_nodes_set.clone(), &ml, idx)))
```

File: secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs [hunk 11]
```diff
@@ -881,447 +882,226 @@ impl SessionTransport for IsolatedSessionTransport {
...
+
+		fn create(
+			mut meta: ShareChangeSessionMeta,
+			admin_public: Public,
+			_: BTreeSet<NodeId>,
+			ml: &MessagesLoop,
+			idx: usize
+		) -> SessionImpl<IsolatedSessionTransport> {
+			let key_storage = ml.key_storage(idx).clone();
+			let key_version = key_storage.get(&meta.id).unwrap().map(|ks| ks.last_version().unwrap().hash.clone());
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs]: `clone()` on `Copy-type`

File: secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs [hunk 12]
```diff
@@ -881,447 +882,226 @@ impl SessionTransport for IsolatedSessionTransport {
...
+
+			meta.self_node_id = ml.node_key_pair(idx).public().clone();
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs]:
```suggestion
			meta.self_node_id = *ml.node_key_pair(idx).public();
```

File: secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs [hunk 13]
```diff
@@ -881,447 +882,226 @@ impl SessionTransport for IsolatedSessionTransport {
...
+			SessionImpl::new(SessionParams {
+				meta: meta.clone(),
+				transport: IsolatedSessionTransport::new(meta.id, key_version, 1, ml.cluster(idx).view().unwrap()),
+				key_storage: key_storage,
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs]:
```suggestion
				key_storage,
```

File: secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs [hunk 14]
```diff
@@ -881,447 +882,226 @@ impl SessionTransport for IsolatedSessionTransport {
...
-		assert_eq!(ml.nodes[&master_node_id].session.initialize(Some(ml.version), Some(new_nodes_set),
-			Some(ml.old_set_signature.clone()),
-			Some(ml.new_set_signature.clone())
-		).unwrap_err(), Error::ServerKeyIsNotFound);
+		// initial 2-of-3 session
+		let gml = generate_key(3, 1);
+
+		// try to add 1 node using this node as a master node
+		let add = vec![Random.generate().unwrap()];
+		let master = add[0].public().clone();
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs]:
```suggestion
		let master = *add[0].public();
```

File: secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs [hunk 15]
```diff
@@ -881,447 +882,226 @@ impl SessionTransport for IsolatedSessionTransport {
...
+
+		// run share add session
+		let master = gml.0.node(0);
+		let node_to_isolate_key_pair = gml.0.node_key_pair(1).clone();
+		let node_to_isolate = gml.0.node(1);
+		let isolated_key_storage = gml.0.key_storage(1).clone();
+		let mut oldest_nodes_set = gml.0.nodes();
+		oldest_nodes_set.remove(&node_to_isolate);
+		let add = (0..add).map(|_| Random.generate().unwrap()).collect::<Vec<_>>();
+		let newest_nodes_set = add.iter().map(|kp| kp.public().clone()).collect::<Vec<_>>();
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs]:
```suggestion
		let newest_nodes_set = add.iter().map(|kp| *kp.public()).collect::<Vec<_>>();
```

File: secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs [hunk 16]
```diff
@@ -881,447 +882,226 @@ impl SessionTransport for IsolatedSessionTransport {
...
 		let version_b = oldest_key_share.versions[1].hash.clone();
 		let version_c = oldest_key_share.versions[2].hash.clone();
 		debug_assert!(version_a != version_b && version_b != version_c);
 
 		debug_assert!(oldest_nodes_set.iter().all(|n| vec![version_a.clone(), version_b.clone(), version_c.clone()] ==
-			ml.nodes[n].key_storage.get(&Default::default()).unwrap().unwrap().versions.iter().map(|v| v.hash.clone()).collect::<Vec<_>>()));
-		debug_assert!(::std::iter::once(&isolated_node_id).all(|n| vec![version_a.clone(), version_c.clone()] ==
-			ml.nodes[n].key_storage.get(&Default::default()).unwrap().unwrap().versions.iter().map(|v| v.hash.clone()).collect::<Vec<_>>()));
+			ml.ml.key_storage_of(n).get(&Default::default()).unwrap().unwrap()
+				.versions.iter().map(|v| v.hash.clone()).collect::<Vec<_>>()));
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs]:
```suggestion
				.versions.iter().map(|v| v.hash).collect::<Vec<_>>()));
```

File: secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs [hunk 17]
```diff
@@ -881,447 +882,226 @@ impl SessionTransport for IsolatedSessionTransport {
...
+		debug_assert!(::std::iter::once(&node_to_isolate).all(|n| vec![version_a.clone(), version_c.clone()] ==
+			ml.ml.key_storage_of(n).get(&Default::default()).unwrap().unwrap()
+				.versions.iter().map(|v| v.hash.clone()).collect::<Vec<_>>()));
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs]:
```suggestion
				.versions.iter().map(|v| v.hash).collect::<Vec<_>>()));
```

File: secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs [hunk 18]
```diff
@@ -881,447 +882,226 @@ impl SessionTransport for IsolatedSessionTransport {
...
 		debug_assert!(newest_nodes_set.iter().all(|n| vec![version_b.clone(), version_c.clone()] ==
-			ml.nodes[n].key_storage.get(&Default::default()).unwrap().unwrap().versions.iter().map(|v| v.hash.clone()).collect::<Vec<_>>()));
+			ml.ml.key_storage_of(n).get(&Default::default()).unwrap().unwrap()
+				.versions.iter().map(|v| v.hash.clone()).collect::<Vec<_>>()));
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs]:
```suggestion
				.versions.iter().map(|v| v.hash).collect::<Vec<_>>()));
```

File: secret_store/src/key_server_cluster/client_sessions/generation_session.rs [hunk 19]
```diff
@@ -940,406 +940,315 @@ fn check_threshold(threshold: usize, nodes: &BTreeSet<NodeId>) -> Result<(), Err
...
-		pub fn first_slave(&self) -> &SessionImpl {
-			&self.nodes.values().nth(1).unwrap().session
+		pub fn session_of(&self, node: &NodeId) -> Arc<SessionImpl> {
+			self.0.sessions_of(node).generation_sessions.first().unwrap()
 		}
 
-		pub fn second_slave(&self) -> &SessionImpl {
-			&self.nodes.values().nth(2).unwrap().session
+		pub fn take_message_confirm_initialization(&self) -> (NodeId, NodeId, ConfirmInitialization) {
+			match self.0.take_message() {
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/client_sessions/generation_session.rs]: `Optional`, but I prefer if/else instead of `pattern match` with only two variants

File: secret_store/src/key_server_cluster/client_sessions/signing_session_ecdsa.rs [hunk 20]
```diff
@@ -1061,253 +1061,112 @@ impl JobTransport for SigningJobTransport {
...
-				acl_storages: acl_storages,
-				version: version,
-			}
+		pub fn init_with_version(self, key_version: Option<H256>) -> Result<(Self, Public, H256), Error> {
+			let message_hash = H256::random();
+			let requester = Random.generate().unwrap();
+			let signature = ethkey::sign(requester.secret(), &SessionId::default()).unwrap();
+			self.0.cluster(0).client()
+				.new_ecdsa_signing_session(Default::default(), signature.into(), key_version, message_hash.clone())
+				.map(|_| (self, requester.public().clone(), message_hash))
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/client_sessions/signing_session_ecdsa.rs]:
```suggestion
				.map(|_| (self, *requester.public(), message_hash))
```

File: secret_store/src/key_server_cluster/client_sessions/signing_session_ecdsa.rs [hunk 21]
```diff
@@ -1061,253 +1061,112 @@ impl JobTransport for SigningJobTransport {
...
-				queue: VecDeque::new(),
-				acl_storages: acl_storages,
-				version: version,
-			}
+		pub fn init_with_version(self, key_version: Option<H256>) -> Result<(Self, Public, H256), Error> {
+			let message_hash = H256::random();
+			let requester = Random.generate().unwrap();
+			let signature = ethkey::sign(requester.secret(), &SessionId::default()).unwrap();
+			self.0.cluster(0).client()
+				.new_ecdsa_signing_session(Default::default(), signature.into(), key_version, message_hash.clone())
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/client_sessions/signing_session_ecdsa.rs]:
```suggestion
				.new_ecdsa_signing_session(Default::default(), signature.into(), key_version, message_hash)
```

File: secret_store/src/key_server_cluster/client_sessions/signing_session_schnorr.rs [hunk 22]
```diff
@@ -809,290 +809,162 @@ impl JobTransport for SigningJobTransport {
...
-			&self.nodes.values().nth(0).unwrap().session
+		pub fn init_with_version(self, key_version: Option<H256>) -> Result<(Self, Public, H256), Error> {
+			let message_hash = H256::random();
+			let requester = Random.generate().unwrap();
+			let signature = ethkey::sign(requester.secret(), &SessionId::default()).unwrap();
+			self.0.cluster(0).client().new_schnorr_signing_session(
+				Default::default(),
+				signature.into(),
+				key_version,
+				message_hash.clone()).map(|_| (self, requester.public().clone(), message_hash))
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/client_sessions/signing_session_schnorr.rs]:
```suggestion
				message_hash).map(|_| (self, *requester.public(), message_hash))
```

File: secret_store/src/key_server_cluster/client_sessions/signing_session_schnorr.rs [hunk 23]
```diff
@@ -809,290 +809,162 @@ impl JobTransport for SigningJobTransport {
...
+		assert_eq!(ml.init().unwrap_err(), Error::ConsensusUnreachable);
 	}
 
 	#[test]
 	fn schnorr_fails_to_initialize_when_already_initialized() {
-		let (_, sl) = prepare_signing_sessions(1, 3);
-		assert_eq!(sl.master().initialize(sl.version.clone(), 777.into()), Ok(()));
-		assert_eq!(sl.master().initialize(sl.version.clone(), 777.into()), Err(Error::InvalidStateForRequest));
+		let (ml, _, _) = MessageLoop::new(1, 0).unwrap().init().unwrap();
+		assert_eq!(ml.session_at(0).initialize(ml.key_version(), 777.into()),
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/client_sessions/signing_session_schnorr.rs]: nit: this fits on a single line (< 120 chars)

File: secret_store/src/key_server_cluster/cluster.rs [hunk 24]
```diff
@@ -137,114 +110,131 @@ pub struct ClusterConfiguration {
...
-	/// Last message time.
-	last_message_time: RwLock<Instant>,
+/// Create new in-memory backed cluster
+#[cfg(test)]
+pub fn new_test_cluster(
+	messages: MessagesQueue,
+	config: ClusterConfiguration,
+) -> Result<Arc<ClusterCore<Arc<TestConnections>>>, Error> {
+	let nodes = config.key_server_set.snapshot().current_set;
+	let connections = new_test_connections(messages, config.self_key_pair.public().clone(), nodes.keys().cloned().collect());
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
	let connections = new_test_connections(messages, *config.self_key_pair.public(), nodes.keys().cloned().collect());
```

File: secret_store/src/key_server_cluster/cluster.rs [hunk 25]
```diff
@@ -137,114 +110,131 @@ pub struct ClusterConfiguration {
...
+		connections: C,
+		servers_set_change_creator_connector: Arc<ServersSetChangeSessionCreatorConnector>,
+		config: ClusterConfiguration,
+	) -> Result<Arc<Self>, Error> {
 		Ok(Arc::new(ClusterCore {
-			listen_address: listen_address,
-			data: data,
+			data: Arc::new(ClusterData {
+				self_key_pair: config.self_key_pair.clone(),
+				connections: connections,
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
				connections,
```

File: secret_store/src/key_server_cluster/cluster.rs [hunk 26]
```diff
@@ -137,114 +110,131 @@ pub struct ClusterConfiguration {
...
+				sessions: sessions.clone(),
+				config: config,
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
				config,
```

File: secret_store/src/key_server_cluster/cluster.rs [hunk 27]
```diff
@@ -1121,44 +483,99 @@ impl ClusterClient for ClusterClientImpl {
...
+	let session_id = match params.session_id {
+		Some(session_id) if session_id == *SERVERS_SET_CHANGE_SESSION_ID => session_id,
+		Some(_) => return Err(Error::InvalidMessage),
+		None => *SERVERS_SET_CHANGE_SESSION_ID,
+	};
+
+	let cluster = create_cluster_view(self_key_pair.clone(), connections, true)?;
+	let creation_data = AdminSessionCreationData::ServersSetChange(params.migration_id, params.new_nodes_set.clone());
+	let session = sessions.admin_sessions
+		.insert(cluster, self_key_pair.public().clone(), session_id, None, true, Some(creation_data))?;
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
		.insert(cluster, *self_key_pair.public(), session_id, None, true, Some(creation_data))?;
```

File: secret_store/src/key_server_cluster/cluster.rs [hunk 28]
```diff
@@ -1263,372 +679,426 @@ pub mod tests {
...
+
+	impl MessagesLoop {
+		/// Returns set of all nodes ids.
+		pub fn nodes(&self) -> BTreeSet<NodeId> {
+			self.clusters_map.keys().cloned().collect()
+		}
+
+		/// Returns nodes id by its index.
+		pub fn node(&self, idx: usize) -> NodeId {
+			self.clusters_map.keys().nth(idx).unwrap().clone()
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
			*self.clusters_map.keys().nth(idx).unwrap()
```

File: secret_store/src/key_server_cluster/cluster.rs [hunk 29]
```diff
@@ -1263,372 +679,426 @@ pub mod tests {
...
+		}
+
+		/// Isolate node from others.
+		pub fn isolate(&self, idx: usize) {
+			let node = self.node(idx);
+			for (i, cluster) in self.clusters_map.values().enumerate() {
+				if i == idx {
+					cluster.data.connections.isolate();
+				} else {
+					cluster.data.connections.disconnect(node.clone());
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
					cluster.data.connections.disconnect(node);
```

File: secret_store/src/key_server_cluster/cluster.rs [hunk 30]
```diff
@@ -1263,372 +679,426 @@ pub mod tests {
...
+				}
+			}
+		}
+
+		/// Exclude node from cluster.
+		pub fn exclude(&mut self, idx: usize) {
+			let node = self.node(idx);
+			for (i, cluster) in self.clusters_map.values().enumerate() {
+				if i != idx {
+					cluster.data.connections.exclude(node.clone());
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
					cluster.data.connections.exclude(node);
```

File: secret_store/src/key_server_cluster/cluster.rs [hunk 31]
```diff
@@ -1263,372 +679,426 @@ pub mod tests {
...
+
+		/// Include new node to the cluster.
+		pub fn include(&mut self, node_key_pair: Arc<PlainNodeKeyPair>) -> usize {
+			let key_storage = Arc::new(DummyKeyStorage::default());
+			let acl_storage = Arc::new(DummyAclStorage::default());
+			let cluster_params = ClusterConfiguration {
+				self_key_pair: node_key_pair.clone(),
+				key_server_set: Arc::new(MapKeyServerSet::new(false, self.nodes().iter()
+					.chain(::std::iter::once(node_key_pair.public()))
+					.map(|n| (n.clone(), format!("127.0.0.1:{}", 13).parse().unwrap()))
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
					.map(|n| (*n, format!("127.0.0.1:{}", 13).parse().unwrap()))
```

File: secret_store/src/key_server_cluster/cluster.rs [hunk 32]
```diff
@@ -1263,372 +679,426 @@ pub mod tests {
...
+				acl_storage: acl_storage.clone(),
+				admin_public: None,
+				preserve_sessions: self.preserve_sessions,
+			};
+			let cluster = new_test_cluster(self.messages.clone(), cluster_params).unwrap();
+
+			for cluster in self.clusters_map.values(){
+				cluster.data.connections.include(node_key_pair.public().clone());
+			}
+			self.acl_storages_map.insert(node_key_pair.public().clone(), acl_storage);
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
			self.acl_storages_map.insert(*node_key_pair.public(), acl_storage);
```

File: secret_store/src/key_server_cluster/cluster.rs [hunk 33]
```diff
@@ -1263,372 +679,426 @@ pub mod tests {
...
+			self.key_storages_map.insert(node_key_pair.public().clone(), key_storage);
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
			self.key_storages_map.insert(*node_key_pair.public(), key_storage);
```

File: secret_store/src/key_server_cluster/cluster.rs [hunk 34]
```diff
@@ -1263,372 +679,426 @@ pub mod tests {
...
+			self.clusters_map.insert(node_key_pair.public().clone(), cluster);
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
			self.clusters_map.insert(*node_key_pair.public(), cluster);
```

File: secret_store/src/key_server_cluster/cluster.rs [hunk 35]
```diff
@@ -1263,372 +679,426 @@ pub mod tests {
...
+			self.key_pairs_map.insert(node_key_pair.public().clone(), node_key_pair.clone());
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
			self.key_pairs_map.insert(*node_key_pair.public(), node_key_pair.clone());
```

Comment (niklasad1) [reply secret_store/src/key_server_cluster/cluster.rs]: You could also `deref` the public key before this in order to avoid cloning `node_key_par` and move it instead!

File: secret_store/src/key_server_cluster/cluster.rs [hunk 36]
```diff
@@ -1263,372 +679,426 @@ pub mod tests {
...
+			self.clusters_map.keys().position(|k| k == node_key_pair.public()).unwrap()
+		}
+
+		/// Is empty messagq queue?
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]: Is the message queue empty?

File: secret_store/src/key_server_cluster/cluster.rs [hunk 37]
```diff
@@ -1263,372 +679,426 @@ pub mod tests {
...
+			.map(|_| Arc::new(PlainNodeKeyPair::new(Random.generate().unwrap()))).collect();
+		let key_storages: Vec<_> = (0..num_nodes).map(|_| Arc::new(DummyKeyStorage::default())).collect();
+		let acl_storages: Vec<_> = (0..num_nodes).map(|_| Arc::new(DummyAclStorage::default())).collect();
 		let cluster_params: Vec<_> = (0..num_nodes).map(|i| ClusterConfiguration {
-			threads: 1,
-			self_key_pair: Arc::new(PlainNodeKeyPair::new(key_pairs[i].clone())),
-			listen_address: ("127.0.0.1".to_owned(), ports_begin + i as u16),
+			self_key_pair: key_pairs[i].clone(),
 			key_server_set: Arc::new(MapKeyServerSet::new(false, key_pairs.iter().enumerate()
 				.map(|(j, kp)| (kp.public().clone(), format!("127.0.0.1:{}", ports_begin + j as u16).parse().unwrap()))
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
				.map(|(j, kp)| (*kp.public(), format!("127.0.0.1:{}", ports_begin + j as u16).parse().unwrap()))
```

File: secret_store/src/key_server_cluster/cluster.rs [hunk 38]
```diff
@@ -1263,372 +679,426 @@ pub mod tests {
...
-	fn cluster_connects_to_other_nodes() {
-		let mut runtime = new_runtime();
-		let clusters = make_clusters(&runtime, 6010, 3);
-		run_clusters(&clusters);
-		let clusters_clone = clusters.clone();
-		loop_until(&mut runtime, TIMEOUT, move || clusters_clone.iter().all(all_connections_established));
-		shutdown_clusters(&clusters);
-		runtime.shutdown_now().wait().unwrap();
+		let clusters_map = clusters.iter().map(|c| (c.data.config.self_key_pair.public().clone(), c.clone())).collect();
+		let key_pairs_map = key_pairs.into_iter().map(|kp| (kp.public().clone(), kp)).collect();
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
		let key_pairs_map = key_pairs.into_iter().map(|kp| (*kp.public(), kp)).collect();
```

File: secret_store/src/key_server_cluster/cluster.rs [hunk 39]
```diff
@@ -1263,372 +679,426 @@ pub mod tests {
...
-	#[test]
-	fn cluster_connects_to_other_nodes() {
-		let mut runtime = new_runtime();
-		let clusters = make_clusters(&runtime, 6010, 3);
-		run_clusters(&clusters);
-		let clusters_clone = clusters.clone();
-		loop_until(&mut runtime, TIMEOUT, move || clusters_clone.iter().all(all_connections_established));
-		shutdown_clusters(&clusters);
-		runtime.shutdown_now().wait().unwrap();
+		let clusters_map = clusters.iter().map(|c| (c.data.config.self_key_pair.public().clone(), c.clone())).collect();
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
		let clusters_map = clusters.iter().map(|c| (*c.data.config.self_key_pair.public(), c.clone())).collect();
```

File: secret_store/src/key_server_cluster/cluster.rs [hunk 40]
```diff
@@ -1263,372 +679,426 @@ pub mod tests {
...
+		let key_pairs_map = key_pairs.into_iter().map(|kp| (kp.public().clone(), kp)).collect();
+		let key_storages_map = clusters.iter().zip(key_storages.into_iter())
+			.map(|(c, ks)| (c.data.config.self_key_pair.public().clone(), ks)).collect();
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
			.map(|(c, ks)| (*c.data.config.self_key_pair.public(), ks)).collect();
```

File: secret_store/src/key_server_cluster/cluster.rs [hunk 41]
```diff
@@ -1263,372 +679,426 @@ pub mod tests {
...
+		let acl_storages_map = clusters.iter().zip(acl_storages.into_iter())
+			.map(|(c, acls)| (c.data.config.self_key_pair.public().clone(), acls)).collect();
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
			.map(|(c, acls)| (*c.data.config.self_key_pair.public(), acls)).collect();
```

File: secret_store/src/key_server_cluster/cluster.rs [hunk 42]
```diff
@@ -1263,372 +679,426 @@ pub mod tests {
...
 	}
 
 	#[test]
 	fn cluster_wont_start_generation_session_if_not_fully_connected() {
-		let runtime = new_runtime();
-		let clusters = make_clusters(&runtime, 6013, 3);
-		clusters[0].run().unwrap();
-		match clusters[0].client().new_generation_session(SessionId::default(), Default::default(), Default::default(), 1) {
+		let ml = make_clusters(3);
+		ml.cluster(0).data.connections.disconnect(ml.cluster(0).data.self_key_pair.public().clone());
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster.rs]:
```suggestion
		ml.cluster(0).data.connections.disconnect(*ml.cluster(0).data.self_key_pair.public());
```

File: secret_store/src/key_server_cluster/cluster_connections.rs [hunk 43]
```diff
@@ -0,0 +1,176 @@
...
+		}
+
+		fn disconnected_nodes(&self) -> BTreeSet<NodeId> {
+			self.disconnected_nodes.lock().clone()
+		}
+
+		fn connection(&self, node: &NodeId) -> Option<Arc<Connection>> {
+			match self.connected_nodes.lock().contains(node) {
+				true => Some(Arc::new(TestConnection {
+					from: self.node.clone(),
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_connections.rs]:
```suggestion
					from: self.node,
```

File: secret_store/src/key_server_cluster/cluster_connections.rs [hunk 44]
```diff
@@ -0,0 +1,176 @@
...
+					to: node.clone(),
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_connections.rs]:
```suggestion
					to: *node,
```

File: secret_store/src/key_server_cluster/cluster_connections.rs [hunk 45]
```diff
@@ -0,0 +1,176 @@
...
+				true => Err(Error::NodeDisconnected),
+			}
+		}
+
+		fn disconnected_nodes(&self) -> BTreeSet<NodeId> {
+			self.disconnected_nodes.lock().clone()
+		}
+
+		fn connection(&self, node: &NodeId) -> Option<Arc<Connection>> {
+			match self.connected_nodes.lock().contains(node) {
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_connections.rs]: Consider replacing with a if/else instead of match!

File: secret_store/src/key_server_cluster/cluster_connections.rs [hunk 46]
```diff
@@ -0,0 +1,176 @@
...
+		fn node_id(&self) -> &NodeId {
+			&self.to
+		}
+
+		fn node_address(&self) -> String {
+			format!("{}", self.to)
+		}
+
+		fn send_message(&self, message: Message) {
+			self.messages.lock().push_back((self.from.clone(), self.to.clone(), message))
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_connections.rs]:
```suggestion
			self.messages.lock().push_back((self.from, self.to, message))
```

File: secret_store/src/key_server_cluster/cluster_connections_net.rs [hunk 47]
```diff
@@ -0,0 +1,543 @@
...
+/// we must treat this node as non-responding && disconnect from it.
+const KEEP_ALIVE_DISCONNECT_INTERVAL: Duration = Duration::from_secs(60);
+
+/// Network connection manager configuration.
+pub struct NetConnectionsManagerConfig {
+	/// Allow connecting to 'higher' nodes.
+	pub allow_connecting_to_higher_nodes: bool,
+	/// Interface to listen to.
+	pub listen_address: (String, u16),
+	/// Should key servers set change session when servers set changes? This
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_connections_net.rs]: Can you rephrase the first sentence? I don't understand it and also both `key servers` and `servers` are used here do they mean the same thing in this context?

I suggest adding a `TODO` here if the question is not sorted out

File: secret_store/src/key_server_cluster/cluster_connections_net.rs [hunk 48]
```diff
@@ -0,0 +1,543 @@
...
+	) -> Result<Self, Error> {
+		let listen_address = make_socket_address(
+			&net_config.listen_address.0,
+			net_config.listen_address.1)?;
+
+		Ok(NetConnectionsManager {
+			listen_address,
+			data: Arc::new(NetConnectionsData {
+				allow_connecting_to_higher_nodes: net_config.allow_connecting_to_higher_nodes,
+				executor: executor,
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_connections_net.rs]:
```suggestion
				executor,
```

File: secret_store/src/key_server_cluster/cluster_connections_net.rs [hunk 49]
```diff
@@ -0,0 +1,543 @@
...
+	fn disconnected_nodes(&self) -> BTreeSet<NodeId> {
+		let connections = self.read();
+		connections.nodes.keys()
+			.filter(|node_id| !connections.connections.contains_key(node_id))
+			.cloned()
+			.collect()
+	}
+
+	fn connection(&self, node: &NodeId) -> Option<Arc<Connection>> {
+		match self.read().connections.get(node).cloned() {
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_connections_net.rs]: Do you really need to pattern match in this?

Isn't `self.read().connections.get(node).cloned()` sufficient?

File: secret_store/src/key_server_cluster/cluster_connections_net.rs [hunk 50]
```diff
@@ -0,0 +1,543 @@
...
+		if container.connections.contains_key(connection.node_id()) {
+			// we have already connected to the same node
+			// the agreement is that node with lower id must establish connection to node with higher id
+			if (self.self_key_pair.public() < connection.node_id() && connection.is_inbound())
+				|| (self.self_key_pair.public() > connection.node_id() && !connection.is_inbound()) {
+				return false;
+			}
+		}
+
+		let node = connection.node_id().clone();
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_connections_net.rs]: connection.node_id() called several times, you could call it once and then pass the node the functions/methods where it is used! But, perhaps the compiler may handle this for you :P 

```suggestion
		let node = *connection.node_id();
```

File: secret_store/src/key_server_cluster/cluster_connections_net.rs [hunk 51]
```diff
@@ -0,0 +1,543 @@
...
+			container.connections.len() + 1, container.nodes.len());
+		container.connections.insert(node, connection);
+
+		true
+	}
+
+	/// Tries to remove connection. Returns true if connection has been removed.
+	/// Returns false if we do not know this connection.
+	pub fn remove(&self, connection: &NetConnection) -> bool {
+		let node_id = connection.node_id().clone();
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_connections_net.rs]:
```suggestion
		let node_id = *connection.node_id();
```

File: secret_store/src/key_server_cluster/cluster_connections_net.rs [hunk 52]
```diff
@@ -0,0 +1,543 @@
...
+		let is_inbound = connection.is_inbound();
+		let mut container = self.container.write();
+		if let Entry::Occupied(entry) = container.connections.entry(node_id.clone()) {
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_connections_net.rs]:
```suggestion
		if let Entry::Occupied(entry) = container.connections.entry(node_id) {
```

File: secret_store/src/key_server_cluster/cluster_connections_net.rs [hunk 53]
```diff
@@ -0,0 +1,543 @@
...
+				let maintain_action = data.trigger.lock().on_connection_established(connection.node_id());
+				maintain_connection_trigger(data.clone(), maintain_action);
+
+				return net_process_connection_messages(data, connection);
+			}
+		},
+		Ok(DeadlineStatus::Meet(Err(err))) => {
+			warn!(target: "secretstore_net", "{}: protocol error '{}' when establishing {} connection{}",
+				data.self_key_pair.public(), err, if outbound_addr.is_some() { "outbound" } else { "inbound" },
+				outbound_addr.map(|a| format!(" with {}", a)).unwrap_or_default());
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_connections_net.rs]: This could be `map_or/map_or_else` (String::new() doesn't allocate so I guess map_or is ok)

File: secret_store/src/key_server_cluster/cluster_connections_net.rs [hunk 54]
```diff
@@ -0,0 +1,543 @@
...
+		},
+		Ok(DeadlineStatus::Timeout) => {
+			warn!(target: "secretstore_net", "{}: timeout when establishing {} connection{}",
+				data.self_key_pair.public(), if outbound_addr.is_some() { "outbound" } else { "inbound" },
+				outbound_addr.map(|a| format!(" with {}", a)).unwrap_or_default());
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_connections_net.rs]: This could be `map_or/map_or_else` (String::new() doesn't allocate so I guess map_or is ok)

File: secret_store/src/key_server_cluster/cluster_connections_net.rs [hunk 55]
```diff
@@ -0,0 +1,543 @@
...
+		},
+		Err(err) => {
+			warn!(target: "secretstore_net", "{}: network error '{}' when establishing {} connection{}",
+				data.self_key_pair.public(), err, if outbound_addr.is_some() { "outbound" } else { "inbound" },
+				outbound_addr.map(|a| format!(" with {}", a)).unwrap_or_default());
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_connections_net.rs]: This could be `map_or/map_or_else` (String::new() doesn't allocate so I guess map_or is ok)

File: secret_store/src/key_server_cluster/cluster_connections_net.rs [hunk 56]
```diff
@@ -0,0 +1,543 @@
...
+					warn!(target: "secretstore_net", "{}: protocol error '{}' when reading message from node {}",
+						data.self_key_pair.public(), err, connection.node_id());
+					// continue serving connection
+					let process_messages_future = net_process_connection_messages(
+							data.clone(), connection).then(|_| Ok(()));
+					execute(&data.executor, process_messages_future);
+					Box::new(future::ok(Err(err)))
+				},
+				Err(err) => {
+					let node_id = connection.node_id().clone();
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_connections_net.rs]:
```suggestion
					let node_id = *connection.node_id();
```

File: secret_store/src/key_server_cluster/cluster_connections_net.rs [hunk 57]
```diff
@@ -0,0 +1,543 @@
...
+fn net_keep_alive(data: Arc<NetConnectionsData>) {
+	let now = Instant::now();
+	let active_connections = data.active_connections();
+	for connection in active_connections {
+		let last_message_diff = now - connection.last_message_time();
+		if last_message_diff > KEEP_ALIVE_DISCONNECT_INTERVAL {
+			warn!(target: "secretstore_net", "{}: keep alive timeout for node {}",
+				data.self_key_pair.public(), connection.node_id());
+
+			let node_id = connection.node_id().clone();
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_connections_net.rs]:
```suggestion
			let node_id = *connection.node_id();
```

File: secret_store/src/key_server_cluster/cluster_connections_net.rs [hunk 58]
```diff
@@ -0,0 +1,543 @@
...
+		}
+	}
+}
+
+/// Connect disconnected nodes.
+fn net_connect_disconnected(data: Arc<NetConnectionsData>) {
+	let disconnected_nodes = data.disconnected_nodes();
+	for (node_id, address) in disconnected_nodes {
+		if data.allow_connecting_to_higher_nodes || *data.self_key_pair.public() < node_id {
+			net_connect(data.clone(), address.clone());
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_connections_net.rs]:
```suggestion
			net_connect(data.clone(), address);
```

File: secret_store/src/key_server_cluster/cluster_connections_net.rs [hunk 59]
```diff
@@ -0,0 +1,543 @@
...
+	pub fn active_connections(&self) -> Vec<Arc<NetConnection>> {
+		self.container.read().connections.values().cloned().collect()
+	}
+
+	/// Executes closure for each disconnected node.
+	pub fn disconnected_nodes(&self) -> Vec<(NodeId, SocketAddr)> {
+		let container = self.container.read();
+		container.nodes.iter()
+			.filter(|(node_id, _)| !container.connections.contains_key(node_id))
+			.map(|(node_id, addr)| (node_id.clone(), addr.clone()))
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_connections_net.rs]:
```suggestion
			.map(|(node_id, addr)| (*node_id, *addr))
```

File: secret_store/src/key_server_cluster/cluster_message_processor.rs [hunk 60]
```diff
@@ -0,0 +1,357 @@
...
+		&self,
+		sessions: &ClusterSessionsContainer<S, SC, D>,
+		connection: Arc<Connection>,
+		mut message: Message,
+	) -> Option<Arc<S>>
+		where
+			Message: IntoSessionId<S::Id>
+	{
+		// get or create new session, if required
+		let mut sender = connection.node_id().clone();
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_message_processor.rs]:
```suggestion
		let mut sender = *connection.node_id();
```

File: secret_store/src/key_server_cluster/cluster_message_processor.rs [hunk 61]
```diff
@@ -0,0 +1,357 @@
...
+				only session messages are passed to prepare_session;
+				qed");
+		let is_initialization_message = message.is_initialization_message();
+		let is_delegation_message = message.is_delegation_message();
+		match is_initialization_message || is_delegation_message {
+			false => sessions.get(&session_id, true).ok_or(Error::NoActiveSessionWithId),
+			true => {
+				let creation_data = SC::creation_data_from_message(&message)?;
+				let master = if is_initialization_message {
+					sender.clone()
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_message_processor.rs]:
```suggestion
					*sender
```

File: secret_store/src/key_server_cluster/cluster_message_processor.rs [hunk 62]
```diff
@@ -0,0 +1,357 @@
...
+				} else {
+					self.self_key_pair.public().clone()
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_message_processor.rs]:
```suggestion
					*self.self_key_pair.public()
```

File: secret_store/src/key_server_cluster/cluster_message_processor.rs [hunk 63]
```diff
@@ -0,0 +1,357 @@
...
+		message: &Message
+	) -> Result<Arc<S>, Error>
+		where
+			Message: IntoSessionId<S::Id>
+	{
+		fn requires_all_connections(message: &Message) -> bool {
+			match *message {
+				Message::Generation(_) => true,
+				Message::ShareAdd(_) => true,
+				Message::ServersSetChange(_) => true,
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_message_processor.rs]: Could be a oneliner `	Message::Generation(_) | Message::ShareAdd(_) | Message::ServersSetChange(_) => true`

File: secret_store/src/key_server_cluster/cluster_message_processor.rs [hunk 64]
```diff
@@ -0,0 +1,357 @@
...
+
+	fn process_connection_message(&self, connection: Arc<Connection>, message: Message) {
+		trace!(target: "secretstore_net", "{}: received message {} from {}",
+			self.self_key_pair.public(), message, connection.node_id());
+
+		// error is ignored as we only process errors on session level
+		match message {
+			Message::Generation(message) => self
+				.process_message(&self.sessions.generation_sessions, connection, Message::Generation(message))
+				.map(|_| ()).unwrap_or_default(),
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/cluster_message_processor.rs]: could be map_or

File: secret_store/src/key_server_cluster/connection_trigger.rs [hunk 65]
```diff
@@ -21,8 +21,10 @@ use std::sync::Arc;
 use ethereum_types::H256;
 use ethkey::Public;
 use key_server_cluster::{KeyServerSet, KeyServerSetSnapshot};
-use key_server_cluster::cluster::{ClusterClient, ClusterConnectionsData};
+use key_server_cluster::cluster::{ClusterConfiguration, ServersSetChangeParams};
 use key_server_cluster::cluster_sessions::AdminSession;
+use key_server_cluster::cluster_connections::{Connection};
+use key_server_cluster::cluster_connections_net::{NetConnectionsContainer};
 use types::{Error, NodeId};
 use {NodeKeyPair};
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/connection_trigger.rs]: unnecessary blocks for single import
```suggestion
use NodeKeyPair;
```

File: secret_store/src/key_server_cluster/connection_trigger.rs [hunk 66]
```diff
@@ -95,6 +97,11 @@ pub struct TriggerConnections {
 }
 
 impl SimpleConnectionTrigger {
+	/// Create new simple from cluster configuration.
+	pub fn with_config(config: &ClusterConfiguration) -> Self {
+		Self::new(config.key_server_set.clone(), config.self_key_pair.clone(), config.admin_public.clone())
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/connection_trigger.rs]:
```suggestion
		Self::new(config.key_server_set.clone(), config.self_key_pair.clone(), config.admin_public)
```

File: secret_store/src/key_server_cluster/connection_trigger.rs [hunk 67]
```diff
@@ -204,13 +216,13 @@ mod tests {
 	use std::collections::BTreeSet;
 	use std::sync::Arc;
 	use ethkey::{Random, Generator};
-	use key_server_cluster::cluster::ClusterConnectionsData;
 	use key_server_cluster::{MapKeyServerSet, PlainNodeKeyPair, KeyServerSetSnapshot, KeyServerSetMigration};
+	use key_server_cluster::cluster_connections_net::{NetConnectionsContainer};
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/connection_trigger.rs]: unnecessary blocks for single import

File: secret_store/src/key_server_cluster/connection_trigger_with_migration.rs [hunk 68]
```diff
@@ -21,7 +21,8 @@ use ethereum_types::H256;
 use ethkey::Public;
 use parking_lot::Mutex;
 use key_server_cluster::{KeyServerSet, KeyServerSetSnapshot, KeyServerSetMigration, is_migration_required};
-use key_server_cluster::cluster::{ClusterClient, ClusterConnectionsData};
+use key_server_cluster::cluster::{ClusterConfiguration, ServersSetChangeParams};
+use key_server_cluster::cluster_connections_net::{NetConnectionsContainer};
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/connection_trigger_with_migration.rs]: unnecessary blocks for single import

File: secret_store/src/key_server_cluster/connection_trigger_with_migration.rs [hunk 69]
```diff
@@ -255,30 +259,42 @@ impl TriggerSession {
...
+		let new_set = old_set.clone();
+
+		let signatures = self.self_key_pair.sign(&ordered_nodes_hash(&old_set))
+			.and_then(|old_set_signature| self.self_key_pair.sign(&ordered_nodes_hash(&new_set))
+				.map(|new_set_signature| (old_set_signature, new_set_signature)));
+
+		match signatures {
+			Ok((old_set_signature, new_set_signature)) => Some(ServersSetChangeParams {
+				session_id: None,
+				migration_id: Some(migration.id.clone()),
```
Comment (niklasad1) [inline secret_store/src/key_server_cluster/connection_trigger_with_migration.rs]:
```suggestion
				migration_id: Some(migration.id),
```

**Comment by 5chdn** [comment]
:+1: needs a 2nd review

**Comment by 5chdn** [comment]
could you rebase this @svyatonik?

who wants to do a 2nd review @grbIzl @seunlanlege?

**Comment by 5chdn** [comment]
Needs a 2nd review :roll_eyes: :laughing:
