### PR TITLE
`gasleft` extern implemented for WASM runtime (kip-6)

### LINKED ISSUE #9276: x-contract-call failed: EVM execution error
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v2.1.0-unstable-1b1941a-20180724
> - **Which operating system?**: Linux Ubuntu 16.04
> - **How installed?**: from source 
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: Parity development chain
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I am trying to use wasm contracts on Parity development chain.
Contract is based on [pwasm-tutorial: step5](https://github.com/paritytech/pwasm-tutorial/tree/master/step-5)
Add one cross-contract function:
```
fn xTotalSupply(&mut self, addr: Address) -> U256 {
    let mut token = TokenClient::new(addr);
    token.totalSupply()
}
```
Call it through web3:
```
var xAddress = "0x60C7BB902469c7C3c258832326c16b7410CC273F";
// x-contract-call
TokenContract.methods.xTotalSupply(xAddress).call().then((b) => {
	console.log("supply of", xAddress, b);
}).catch(console.log);
```
**note**
Contract was built by `nightly-2018-07-24`.
Current `TokenContract` and `TokenContract` on `xAddress` are both successfully deployed.
Directly call `totalSupply` method of `xAddress` works well and return 10000000. 
Other methods which don't have x-contract-calls works well.

**expected behavior**
print a supply of `xAddress` like `supply of 0x60C7BB902469c7C3c258832326c16b7410CC273F 10000000`

**actual**
web3:
```
Error: Returned error: VM execution error.
    at Object.ErrorResponse (/home/zqz/Documents/pwasm-tutorial/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /home/zqz/Documents/pwasm-tutorial/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/home/zqz/Documents/pwasm-tutorial/node_modules/web3-providers-http/src/index.js:77:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/zqz/Documents/pwasm-tutorial/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/zqz/Documents/pwasm-tutorial/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/zqz/Documents/pwasm-tutorial/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/home/zqz/Documents/pwasm-tutorial/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
Parity
```
2018-08-03 11:23:35   TRACE executive  ext.schedule.have_delegate_call: true
2018-08-03 11:23:35   TRACE wasm  Contract requested 2 pages of initial memory
2018-08-03 11:23:35   TRACE wasm  Contract custom panic message: <msg was stripped>, <unknown>:0:0
2018-08-03 11:23:35   TRACE wasm  Error executing contract: Trap(Trap { kind: Host(Panic("<msg was stripped>, <unknown>:0:0")) })
2018-08-03 11:23:35   TRACE executive  res=Err(Wasm("Wasm runtime error: Trap(Trap { kind: Host(Panic(\"<msg was stripped>, <unknown>:0:0\")) })"))
2018-08-03 11:23:35   TRACE executive  substate=Substate { suicides: {}, touched: {0xb7c78ed23bb1fd46ab6a2e1dda1fa08e0b940bba, 0x004ec07d2329997267ec62b4166639513386f32e}, logs: [], sstore_clears_count: 0x0, contracts_created: [] }; unconfirmed_substate=Substate { suicides: {}, touched: {}, logs: [], sstore_clears_count: 0x0, contracts_created: [] }

2018-08-03 11:23:35   TRACE executive  enacted: substate=Substate { suicides: {}, touched: {0xb7c78ed23bb1fd46ab6a2e1dda1fa08e0b940bba, 0x004ec07d2329997267ec62b4166639513386f32e}, logs: [], sstore_clears_count: 0x0, contracts_created: [] }
```

**step to reproduce**
Just use x-contract-calls. Maybe my way is wrong. I am not sure which module is responsible for this, sorry if this issue belongs another repo.

### PR DESCRIPTION
**Pull request by fckt**
* `wasmGasleftActivationTransition` chainspec parameter added
* `gasleft` extern implemented
* Wasm tests updated

fixes #9276 

https://github.com/kovan-testnet/KIPs/pull/6

### CODE REVIEW

File: json/src/spec/params.rs [hunk 1]
```diff
@@ -152,6 +152,9 @@ pub struct Params {
 	/// KIP4 activiation block height.
 	#[serde(rename="kip4Transition")]
 	pub kip4_transition: Option<Uint>,
+	/// Wasm `gasleft` extern (aka opcode) activation block height.
+	#[serde(rename="wasmGasleftActivationTransition")]
+	pub wasm_gasleft_activation_transition: Option<Uint>,
```
Comment (NikVolf) [inline json/src/spec/params.rs]: i wonder if we can bind it to kip4_transition

how about extending kip4, since it is not activated so far

@debris @sorpaas  ?

Comment (pepyakin) [reply json/src/spec/params.rs]: Agree that we can use 1 switch for that. However, I think we should update the KIP4 proposal itself. Otherwise, it might be very confusing

Comment (NikVolf) [reply json/src/spec/params.rs]: Yeah, I will add another kip then

File: ethcore/src/spec/spec.rs [hunk 2]
```diff
@@ -194,6 +194,7 @@ impl CommonParams {
 			let mut wasm = ::vm::WasmCosts::default();
 			if block_number >= self.kip4_transition {
```
Comment (NikVolf) [inline ethcore/src/spec/spec.rs]: should be `kip6_transition`, right?

we've created separate kip for that

Comment (fckt) [reply ethcore/src/spec/spec.rs]: it’s approved? 🙂

Comment (NikVolf) [reply ethcore/src/spec/spec.rs]: if it will get updated, we'll update the code

it won't be in effect until chainspec changed

File: json/src/spec/params.rs (hunk 1 above)
Comment (NikVolf) [reply json/src/spec/params.rs]: so now it is 2 switches, but they can be activated at once (with the same block number)

please review @pepyakin @sorpaas

**Comment by pepyakin** [comment]
I have a little concern about [`gasleft`](https://github.com/paritytech/pwasm-ethereum/blob/65ccb87c1f89c097639a9fa6f8798a01de65bb1e/src/ext.rs#L259) extern in parity-ethereum: it doesn't have a feature gate.

**Comment by fckt** [comment]
> I have a little concern about gasleft extern in parity-ethereum: it doesn't have a feature gate.

it's strictly necessary to have you think?

File: ethcore/vm/src/schedule.rs [hunk 3]
```diff
@@ -151,6 +151,8 @@ pub struct WasmCosts {
 	pub opcodes_div: u32,
 	/// Whether create2 extern function is activated.
 	pub have_create2: bool,
+	/// Does it have a GASLEFT instruction
```
Comment (pepyakin) [inline ethcore/vm/src/schedule.rs]: I'm not sure why it is referred as a "GASLEFT instruction". I believe it may be quite confusing: GASLEFT is a real concept yet which has nothing to do with wasm which instruction set isn't affect by the KIP6.

Better to borrow wording from the field above.

File: ethcore/wasm/src/tests.rs [hunk 4]
```diff
@@ -815,6 +815,47 @@ fn externs() {
...
+			assert_eq!(gas, 93_420);
+			assert_eq!(gas_left, U256::from(93_343));
+		},
+	}
+}
+
+// This test should fail because
+// ext.schedule.wasm.as_mut().unwrap().have_gasleft = false;
+#[test]
+fn gasleft_panic() {
```
[the remark this answers is not in the document]
Comment (fckt) [reply ethcore/wasm/src/tests.rs]: it was panicking initially. So the idea is to test that it should fail in case `have_gasleft` is not enabled.

File: ethcore/wasm/src/tests.rs [hunk 5]
```diff
@@ -815,6 +815,47 @@ fn externs() {
...
+	::ethcore_logger::init_log();
+
+	let mut params = ActionParams::default();
+	params.gas = U256::from(100_000);
+	params.code = Some(Arc::new(load_sample!("gasleft.wasm")));
+	let mut ext = FakeExt::new().with_wasm();
+	let mut interpreter = wasm_interpreter(params);
+	match interpreter.exec(&mut ext) {
+		Err(..) => {},
+		Ok(..) => panic!("interpreter.exec should return Err if ext.schedule.wasm.have_gasleft = false")
```
[the remark this answers is not in the document]
Comment (fckt) [reply ethcore/wasm/src/tests.rs]: we don't care about data here..

**Comment by pepyakin** [comment]
> it's strictly necessary to have you think?

Now, after KIP4 [set a precedent](https://github.com/paritytech/pwasm-ethereum/pull/12), I think it's quite desirable.

**Comment by fckt** [comment]
> Now, after KIP4 set a precedent, I think it's quite desirable.

makes sense

File: ethcore/wasm/src/tests.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (pepyakin) [reply ethcore/wasm/src/tests.rs]: Yeah, and I'm saying that when we don't care about data we [use](https://github.com/paritytech/parity-ethereum/pull/9357/files#diff-49069a827173f5fdfe15066772243f0aR833) underscore, like:

[the remark this answers is not in the document]
Comment (fckt) [reply ethcore/wasm/src/tests.rs]: so, I guess, the difference here is that in this specific code we also want to not care about argument arity as well

File: ethcore/wasm/src/tests.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (pepyakin) [reply ethcore/wasm/src/tests.rs]: Yes, I can see what this test tests, but still can't see what it has to do with panics. I would rather go with `_fail` at least.

File: ethcore/wasm/src/env.rs [hunk 6]
```diff
@@ -207,6 +213,7 @@ pub struct ImportResolver {
 	memory: RefCell<Option<MemoryRef>>,
 
 	have_create2: bool,
+	have_gasleft: bool,
```
Comment (NikVolf) [inline ethcore/wasm/src/env.rs]: better to rename this to `has_gasleft` and the one above to `has_create2` for consistency

**Comment by NikVolf** [comment]
Also there should be a test that ensures that you can make a call passing exactly `gasleft` gas into it

File: ethcore/wasm/src/env.rs (hunk 6 above)
Comment (fckt) [reply ethcore/wasm/src/env.rs]: shall we rename everything else in the stack https://github.com/paritytech/parity-ethereum/blob/108590d924bcc00e62b894de02516ffb2378be11/ethcore/src/spec/spec.rs#L177 ?

Comment (NikVolf) [reply ethcore/wasm/src/env.rs]: oh, i didn't realized

probably not :)

File: ethcore/wasm/src/tests.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (NikVolf) [reply ethcore/wasm/src/tests.rs]: should be `Ok(_)` / `Err(_)` indeed, like in the rest of the codebase

File: ethcore/vm/src/schedule.rs (hunk 3 above)
Comment (NikVolf) [reply ethcore/vm/src/schedule.rs]: GASLEFT is indeed not an opcode and should not be referred as such

File: ethcore/wasm/src/tests.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (fckt) [reply ethcore/wasm/src/tests.rs]: it's not a "rest of the codebase". It's a concrete code, within its concrete context, which I explained above https://github.com/paritytech/parity-ethereum/pull/9357#discussion_r211572507

[the remark this answers is not in the document]
Comment (fckt) [reply ethcore/wasm/src/tests.rs]: oh, doesn't matter
