### PR TITLE
Fix json tracer overflow

### LINKED ISSUE #9872: Report of potential bug in the parity-evm implementation
Hello, 

- Parity Ethereum version: Parity-Ethereum/v2.2.0-nightly-f4c421f77-20181024/x86_64-linux-gnu/rustc1.29.2 
- Git comment: f4c421f77a1d427b3d22132
- Operating system: Ubuntu 18.04
- Fully synchronized: NA
- Network: NA
- Restarted: NA

Please see the exception info below:

====================
stack backtrace:
  
     0:     0x559de87a428c - backtrace::backtrace::trace::h6cfa6ca381623be3
    1:     0x559de87a4042 - <backtrace::capture::Backtrace as core::default::Default>::default::h1d0ec977487dc5d9
    2:     0x559de87a40b8 - backtrace::capture::Backtrace::new::h3ed6ab535d7c4949
    3:     0x559de847b4ee - panic_hook::gen_panic_msg::ha391f3dfcede76a5
    4:     0x559de847b2e0 - panic_hook::set_with::{{closure}}::haeca7e1698668ad7
    5:     0x559de8948263 - std::panicking::rust_panic_with_hook::h542dacac3f3a20d8
                        at libstd/panicking.rs:479
    6:     0x559de8947dc9 - std::panicking::continue_panic_fmt::hd989cd729c0c5a4b
                        at libstd/panicking.rs:390
    7:     0x559de8947cc5 - rust_begin_unwind
                        at libstd/panicking.rs:325
    8:     0x559de899bf9b - core::panicking::panic_fmt::h26b7cf0675909ac6
                        at libcore/panicking.rs:77
    9:     0x559de8993880 - core::slice::slice_index_len_fail::hcc13d5324deb5495
                        at libcore/slice/mod.rs:1971
    10:     0x559de845923a - <parity_evm::display::json::Informant as ethcore::trace::VMTracer>::trace_executed::{{closure}}::h5e935cd02e455dd8
    11:     0x559de8459887 - <parity_evm::display::json::Informant as ethcore::trace::VMTracer>::drain::h78f1d52c535a2ec1
    12:     0x559de84566de - parity_evm::display::json::Informant::with_informant_in_depth::h6a7ab9f5f3635889
    13:     0x559de840e2d3 - <ethcore::executive::Executive<'a, B>>::call_with_stack_depth::hb9f3b5c7ffe51e5b
    14:     0x559de8401786 - ethcore::client::evm_test_client::EvmTestClient::call::hdb9edaeb8a954e14
    15:     0x559de845080d - parity_evm::info::run_action::h6457e88c2692f821
    16:     0x559de83de0d3 - parity_evm::main::h014ba30bda7cb632
    17:     0x559de8444092 - std::rt::lang_start::{{closure}}::hb0d0ec881d3d75e0
    18:     0x559de8947c62 - std::rt::lang_start_internal::{{closure}}::h2d27f966df62f613
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::h0208f3354fcc3e87
                        at libstd/panicking.rs:310
    19:     0x55aed66b6769 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
    20:     0x55aed66997e5 - std::panicking::try::h8cfae114cfc320aa
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::h9e48b3e6dc9f9394
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::h56481fc9d09c36f4
                        at libstd/rt.rs:58
    21:     0x55aed61308d3 - main
    22:     0x7fe409028b96 - __libc_start_main
    23:     0x55aed606aaf9 - _start
    24:                0x0 - <unknown>

    Thread 'main' panicked at 'index 1048605 out of range for slice of length 0', libcore/slice/mod.rs:1971

    This is a bug. Please report it at:

      https://github.com/paritytech/parity-ethereum/issues/new

    [1]    9408 abort      ./parity-evm --code 5A51 --json --gas fffff

### PR DESCRIPTION
**Pull request by sorpaas**
Fixes #9872 by resizing the memory in case of overflow.

The current logic in json tracer does an artificial `trace_executed` on VM error return, within which the previous `trace_prepare_execute`'s `mem_written` might not be valid. This is replaced by a direct trace push.

### CODE REVIEW

**Comment by sorpaas** [comment]
Having issues for this PR at this moment. As @cheme pointed out the bug is still present!

**Comment by ordian** [comment]
Doesn't seem to fix the issue, please add a test:
```rust
		run_test(
			Informant::default(),
			&compare_json,
			"5A51",
			0xfffff,
			r#"
...
"#,
		)
```

File: evmbin/src/display/json.rs [hunk 1]
```diff
@@ -125,7 +125,6 @@ impl trace::VMTracer for Informant {
 	fn trace_executed(&mut self, gas_used: U256, stack_push: &[U256], mem: &[u8]) {
```
Comment (cheme) [inline evmbin/src/display/json.rs]: I think this function is not use anymore, also :
    display::json::tests::should_trace_create_correctly
    display::json::tests::should_trace_failure
fails for me (for first case it looks like value of the tests was wrong before).

Comment (cheme) [reply evmbin/src/display/json.rs]: Also running the command :  
```parity-evm --code 5A51 --json --gas fffff```
works fine

File: evmbin/src/display/json.rs [hunk 2]
```diff
@@ -195,7 +194,24 @@ impl trace::VMTracer for Informant {
 			// print last line with final state:
 			self.gas_cost = 0.into();
 			let gas_used = self.gas_used;
-			self.trace_executed(gas_used, &[], &[]);
+			let subdepth = self.subdepth;
+
+			Self::with_informant_in_depth(&mut self, subdepth, |informant: &mut Informant| {
+				let info = ::evm::Instruction::from_u8(informant.instruction).map(|i| i.info());
+
+				let trace = json!({
```
Comment (tomusdrw) [inline evmbin/src/display/json.rs]: Any way we could get rid of this duplication? It's not strongly typed and having two places where this is generated is imho error prone in the long term.

File: evmbin/src/display/json.rs (hunk 1 above)
Comment (sorpaas) [reply evmbin/src/display/json.rs]: This is part of the interface for `VMTracer`, which is used in executive and externalities. I don't think we can remove them at this moment!

> fails for me (for first case it looks like value of the tests was wrong before)

That's really weird again! Here's what I got on commit https://github.com/paritytech/parity-ethereum/pull/9873/commits/514d0f1b23d696be569e5d181e9663e851bab379, please double check if I got anything wrong:

```
[nix-shell:~/repos/parity/evmbin]$ cargo test
warning: path override for crate `ring` has altered the original list of
dependencies; the dependency on `libc` was either added or
modified to not match the previously resolved version

This is currently allowed but is known to produce buggy behavior with spurious
recompiles and changes to the crate graph. Path overrides unfortunately were
never intended to support this feature, so for now this message is just a
warning. In the future, however, this message will become a hard error.

To change the dependency graph via an override it's recommended to use the
`[replace]` feature of Cargo instead of the path override feature. This is
documented online at the url below for more information.

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#overriding-dependencies

    Updating crates.io index
   Compiling evmbin v0.1.0 (/home/sorpaas/repos/parity/evmbin)                                                                                                                                                     
    Finished dev [unoptimized + debuginfo] target(s) in 14.03s                                                                                                                                                     
     Running /home/sorpaas/repos/parity/target/debug/deps/parity_evm-18f37a82dbda605a

running 7 tests
test display::std_json::tests::should_trace_create_correctly ... ok
test info::tests::should_call_account_from_spec ... ok
test tests::should_parse_all_the_options ... ok
test tests::should_parse_state_test_command ... ok
test display::std_json::tests::should_trace_failure ... ok
test display::json::tests::should_trace_create_correctly ... ok
test display::json::tests::should_trace_failure ... ok

test result: ok. 7 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

Comment (cheme) [reply evmbin/src/display/json.rs]: Sorry, I should have push another message instead of the edit of the comment, all is fine :+1:
