### PR TITLE
evmbin: Fix gas_used issue in state root mismatch and handle output better

### LINKED ISSUE #9408: Parity-evm: handle failing statetests
I'm doing some fuzzing using statetests that are not properly 'filled', meaning that they do not have a proper post-state. This makes Parity (`parity-evm`) behave a bit oddly. 

## How parity-evm does
When `parity-evm` is executed against a bad test, it behaves oddly.

```
# /parity-evm state-test --std-json /testfiles/martin-Thu_22_42_11-15624-7-test.json

/ $  /parity-evm state-test --std-json /testfiles/martin-Fri_08_26_26-10380-8-test.json
{"test":"randomStatetestmartin-Fri_08_26_26-10380-8:byzantium:0","action":"starting"}
{"pc":0,"op":0,"opName":"STOP","gas":"0x28b38d","stack":[],"storage":{},"depth":1}
{"error":"State root mismatch (got: 0x6bba…662f, expected: 0x0000…c0de)","gasUsed":"1c5c4b36b03a23","time":114}
```

1. It has an erroneous `gasUsed`-value: `1c5c4b36b03a23` 
2. The calculated `stateRoot` cannot be read from the output, since it's obfuscated by ellipsis (`0x6bba…662f`). 

For reference, here's how it looks if the test is fixed with a correct `postState`:

```
/ $  /parity-evm state-test --std-json /testfiles/fixed.json 
{"test":"randomStatetestmartin-Fri_08_26_26-10380-8:byzantium:0","action":"starting"}
{"pc":0,"op":0,"opName":"STOP","gas":"0x28b38d","stack":[],"storage":{},"depth":1}
{"stateRoot":"0x6bba9f22296aa9817a905f737f7edc8d6ab00c337d333a90e972778746a9662f"}
{"output":"0x","gasUsed":"1c5c4b36878696","time":108}
```
## How geth does

Geth separates the `jsonl` output and the actual test results, so that if we want to compare traces, we only need to look at the `stderr`. 

Geth (`stdout`):
```
/ # evm --json --nomemory statetest /testfiles/fixed.json 2>/dev/null
[
  {
    "name": "randomStatetestmartin-Fri_08_26_26-10380-8",
    "pass": true,
    "fork": "Byzantium"
  }
]
```
Geth (`stderr`)
```
/ # evm --json --nomemory statetest /testfiles/fixed.json 1>/dev/null
{"pc":0,"op":0,"gas":"0x28b38d","gasCost":"0x0","memory":"0x","memSize":0,"stack":[],"depth":1,"opName":"STOP","error":""}
{"output":"","gasUsed":"0x0","time":77132}
{"stateRoot": "6bba9f22296aa9817a905f737f7edc8d6ab00c337d333a90e972778746a9662f"}

```

When run against a failing test:

`stdout`: 
```
/ # evm --json --nomemory statetest /testfiles/martin-Fri_08_26_26-10380-8-test.json  2>/dev/null
[
  {
    "name": "randomStatetestmartin-Fri_08_26_26-10380-8",
    "pass": false,
    "fork": "Byzantium",
    "error": "post state root mismatch: got 6bba9f22296aa9817a905f737f7edc8d6ab00c337d333a90e972778746a9662f, want 00000000000000000000000000000000000000000000000000000000deadc0de"
  }
]
```
`stderr`: 
```
/ # evm --json --nomemory statetest /testfiles/martin-Fri_08_26_26-10380-8-test.json  1>/dev/null
{"pc":0,"op":0,"gas":"0x28b38d","gasCost":"0x0","memory":"0x","memSize":0,"stack":[],"depth":1,"opName":"STOP","error":""}
{"output":"","gasUsed":"0x0","time":65381}
{"stateRoot": "6bba9f22296aa9817a905f737f7edc8d6ab00c337d333a90e972778746a9662f"}
```

### What should be done

* Fix the `gasUsed` error
* Make the `postState` readable even if the test fails
* Feature-request: move the `jsonl` trace output to `stderr`, and use `stdout` for the high-level info about whether the actual test failed or succeeded.   

### Complementary info

Failing (broken) testcase json
```json
{"randomStatetestmartin-Fri_08_26_26-10380-8": {"_fuzz": {"compressed_random_state": null}, "env": {"currentCoinbase": "0xc94f5374fce5edbc8e2a8697c15331677e6ebf0b", "currentDifficulty": "0x20000", "currentGasLimit": "0x1c5c4b36b03a23", "currentNumber": "1", "currentTimestamp": "1000", "previousHash": "cd22669921cc9831b5e8f3626c8bc30a0a0ee1b45237fbc5883239c1149654de"}, "post": {"Byzantium": [{"hash": "0x00000000000000000000000000000000000000000000000000000000deadc0de", "logs": "1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "indexes": {"data": 0, "gas": 0, "value": 0}}]}, "pre": {"ffffffffffffffffffffffffffffffffffffffff": {"balance": "0x81a8d5340b222e1f", "code": "0x60f50a60606057004087026140c0ee470000f3616057013b1e60576132360300030061140000c00081b66060006032fb60c23580146060006000008060250000000420600080478200000080601e37410000001e87b5358057360030c000196061605a5b01005763391461d500000069000000f5605900b400140004a5b6000a16de00017461916082131c6090500055901460652001506060000a0200ff001f1f0490ff3d6082818182600a544264000054143183158152522061cb511cff0102541502165084da80ff03522d00910a549852ff54339180ffa750fff292005761816120ff40e854f260ff260091529984906160006181560392d1688001815080601d6063025061ff83320001013557908060501002338de6ff6e816035da12ff40fe5605400016b1ff528315eb2a609260ff6052600d5002010a515015604701810190639081390a01c8010202905280ff026060601663010a03800066e5ffff005193600181529043601090012090746150906083616061065b6083805780ea3a5ed501ff090200157304ff602004615a01ff0a01565401916090549060838202500060ff4f28900790516000560314ff110101601509ff03618148905b86910250906192246060086154601f60906082ff018160ff500a1000e050f061838836c020ff60405bff57525114eaec60158160ffff01616180605b6042606061405bff15f290ff6086ff01f3600100039057842063f2822060076065ff60ea016000ff60a08193905bff160360606061bd60800090ff012004156091511881ff610c908100431460008150605261c9605161606e5580008220f390b36f61507fff60606080ff01055000c0bf021460f191005005614e00205460ffff010aa00417ff57ff606090003a55a1009324156163018740190120900b9560c050800183ff504400000820829020605000870061ff006011f0e85b01ffc0406160ff00209091815b9061540050936110ff605e60938151001691a002046100208160ff0152615b80205181906d02607f8310606073200283500020900681165600ff0141033301e290ffffffff50906090095ba08061ffff8c810003ff0080131001ff83600290ff8191605b01015b619000021961012484ff500390468649002360f3508001918c0001600ec0ff030003000f5102806180ff515b001f6001810450616101ff2060005150859b3940f15420820188618032ff20ff61603512108255021660ff406000ab605460ff8256600335615a5160000a14959001ff81048091cca0010150800aff0090520004548990510151ef600191ff02606080b08755605002f350521990601682028003228a505081905b905b54ff905b006190006320525b03e00001320204005200006150ff241650619000ff608020606000989681907f90146084090040cd0b04ff00568195805190804079e0605100096081ffff20374973600157ffff5602150060da0282a19060836060613e600073910a8163909017016091f354560a809490958102f99185336100ff0461ff90de818174606156021d15b5ff526100619150500114420157ff0100825191ff5bff543701556101aa6161575aff600b60d9603657600060030191527fff098220ff200292c300a0509060696d6002843502219001a681ffffcd6014638a00db016052010050ff60814608040b03547200ff201460509090509005335e814161028557ff91ff2057485a02525000639001605690158051200d572004015bffffff935b001660010020901fff0000f19063c502001660015b00f201ff60e090200100ff8190600052605b90735681208181ff8060ffe0186d2051ffff5b60609150ff600020010160828080b18003ae9090812060ff525073f1011e608301a08082609150ff5501015b7314730024da506b5b451250809056feeb610140353f8c8003855a3604005003010360515090171301605000f3ffae2800ff60608257f2010e83907900006054515bffb0ff0002ff035461570052566060ef033316608223609046ff01ffffff80ff6102608303ff606360575b60865b52802060615cb1169351ff7d573783e0fe6060012060ff7561ff15aa20028191820182002020934057ff600061520110ef600a01b0848361600102005b80818120608382006090ffc919615657f954184c161a511001cf50ff945bff026052ff90026d5af101ff906091ff60618204906000618328545201601d57616115d1600000e8ff3856ff04ffc201905181ff9201206301821582e0f34f92810091ff2060360344505b59209183001e025090609180c2576009ff0082ff016b206f0457208090ff14935017c482ae501480810120605060501655915027ff8061365bff90908037f1609056ff005ac203b00aa461920101119060013667600154ffff502019b86160405000cd6015228160880136ffff22da1eff17", "nonce": "0x41", "storage": {}}, "1000000000000000000000000000000000000000": {"balance": "0x6040eccc26c15681", "code": "0x0000570300800080000000006100e400d25257376132000461201504e1410019015b476060003261000000008f00220065006157590014600000000036351535578057074057735700040000e5c257577cff6052007a6180600000004415605700400014b5000a6360802300006000008854b300006161005781801400610a60556360906100150a8106196040525a200201600154010260605bff5b636093ff6080b703575b82ff6100ffd35b006000806060000150ff60e3906091600110fad300508190168102684c01925661610082817460046090ffff54455403635120020b5715ff608140008250fa2080601601545a906346ff01ff165160ff3f6120155ba2145120ff906060806081ff870160ff61ff0060ff835b635401001790ff20ffff9001186160916054108181a0ff18ff033b0150ff56ff0150828250608083406091601678e8ff1556812281a5900140ff016cff60009050971920ff9a012083c060839005161460608256ffff5040ff544d06ff638060ff915b5b4000001f60600061966060038402ffa050950301505051ff9420169b94ff61ee52006050619160190004f95104118200612056510100906090012046516050606183ff0101a0ff60cf5450a9a1009060ff60c451848580606050818a500201915660ff885b1483ff12ff0340d656ff523559d53e09355591828815009891021a6f005aef81820b1350845161002482200103608200206001505b57ff20206050245b51a256f1014060ff5b0016018052ce001963006191ff82909114015063545001f50a61ff6060009083901e5f011461ff61509190800af72bf70160825157ff003a010507ff575b0052825400d950ff905700829181ff54ff0160ff82cc52818160500883ffab02808092f3005bff90010011601581035435a623020eff56600131523e570403ff90ff005b54515502562003326016627581500003605101565b605a602014616001155bff6000209112115b60c28059fd83bf605a00ff2c1101005060828790ff16a034e47a22690a3a50810191505260eed261fe906057809156fff250208fb3606025605bffd2d282aa606060190736505050ff8360525016025021204b205060ff508182", "nonce": "0x41", "storage": {}}, "b94f5374fce5edbc8e2a8697c15331677e6ebf0b": {"balance": "0x3a1c26dccf5a6aca", "code": "0x036314048100609000000a617c005763350000633c40635a005700017f000100040031000a24570000401460de600000ee000057005a0000160052a225003661366081376087400063040081007c80d20036003727158001b504f8573e00636000350160000460002d603c600441b500631400613539006000a000000035f20091885100ffffff84608380020175cb1580a00013405014000239205204145b600088ff900190ff5090ff5061b55b5bff9120901991ff00036250926062401350504e600801d260900051ffff162a0063ff5650ff020050a71d0c311f035b83638340815090ff90605bff2052816060035bf100024090ff465260815b60615ce70283166220bf0a94ff15019250601460825b406001ff208e0160405051515700176360ff016081901f90736060c601b082903593fff0606076011b560ad6ff63ffffe8a7332060033481ff365a600660502001818483ae1601a11001ff8133816060015015ff01a500419160ff514001cc0264006070816061ffffff809583ff61148950ff009060808120ff821084ff812d81f21d606086ff8402ff05602019ff7f8651009802006050ff63016060736102044903809100ff605004f05083018417845261500101ff00836102565b5038ff60208100ff84610135ff0a32176861910051e000335152b30090ff5b005bff905b81020160ff00381695030e6161a91663ff011215cb576060008402ff00ff50576081ffff2f505680ff600090009060606060613540476035b6575b00420050ff60825290600006f5509060ff0603ffffffc3ff6180870000ff5b01526023010081556156521f5bff0192906060d10080ff810a824001610191600d00ff0080ffb2ff500e009020015515720301564001a09080ff9060ff908455801d63025160202054811601008210040157011409ff9120903455009273606d5004ff0373015221566024ffe015930a14ff60605050816160a96081504a609160ff4e1650510111036181f3025790505a206060905086ff61e600600000202004ff0320960284ff60006004376090200020032004601786015000606501ffff028190a1155b3300526001601460749023568261600050ff9000800950ff8201f5000316608d54ffff6092011505400192b3005bff90526360606e605b906083e1d62057900a7f815060010160570000444c01ff20915bf35090518024ff1600165b200052615b812081568251016083338151018107925b60ff80600180176002910120010000008561ff81008004506d90db6060025116b19000632502600490738100ff48600300576061021440e7503582500039e45291aa572411008691836057505501406101505682508160518182ff006100526061001f9001000060559004e800ff827e6052cb4073ff52ff566081521f5404ff01000100ff11b0900a500e8050006057905069c190605a52323393a1da900105a0618020948244ff81ff11560020ba56004000605401150290ff68606847029301005a5082011400ca1651ff02905ba6156015ff608202ff90ff20ff60607301605b0780f1350096d250510091015b0a8550ffb71400061689ff5b835460544060ff600d60000155011592506000005400506981605261a960837a008212615000609063ffff005001ff8260ffff866082e1ffff5457007d005650612901610050616152ff00ff815d50c00700606dff8260031f1060000a55515b60125073910071036c6045ff0260525016560060005b00844006915701000004919052af20505e8064608156523482601561f3b4500061739901910210ffff57160057ff607351ff608dff505a0403020020901405ff52ff500116609517c85b5757c48001100701ff60635260ff438161518061508361606057da20ff5a8b91086008600e013251008060005183192040600750511560ff525000007301820301a073ff696172601582a0830204921e835bff0260801000827e1636ff61188150fb00900a2005900160ff009050ffff920e605061ff805d601f14035292605240827f0080c452006054ff91603d606101aef3166005605214043890500082ff577c50ac90820a0108918390fff95bff28166190035090ff2090c2816560162060818020323644ff6060000aff60616100ff005b5281600291606180910181a006ff60ff80905060160160ffff60524402f3d8601f60802060088080005bff02730790600050aa011f1eff884059562050546020610082ee566060a760ff505781010137555150ff615b2061605a955461605660220891500357506050b35656237539876060911e5060749204028d905b0a1f800120f15b606060d981926050271f22509203907f020c5704510a2001528803900019d90150a52004220285fc5081609140", "nonce": "0x41", "storage": {}}, "c94f5374fce5edbc8e2a8697c15331677e6ebf0b": {"balance": "0xf1f2dc605bdffa08", "code": "0x52730000010400a4d200528102616036000100150036d2630000600024026000be600080d757611481190061190063e000004160b6048700b60061040a007336c0142061906000600036363500570000810000f400c000010400d202171d147c0000005b0063607c046037603960000035592e008c006d0f616100c70001000060e6f7905b92500203605660568300188560018203606037f00351030120908300638084026116908040030183000061b7015292ea1aa05402540061205750823818ff6152500390f301015200920a9057509091858050ff140060a3925701826081906050156701208001015150001160010060017f814081ae008461155700807f005bc5905061ff6082161460ffe461200a118d90910300360998605131015035ae11f161ffff5b163510ff518a505250e0525bff600a90fe605561ff60508185553161ff5091b3ff6157555020ff0080555230505b5b00ff7e0bff815001960360611686154944ff400020028051609162513560ffffff005b6190520a609011ff900101900050615080908252836168ff1dff6002600a94bb009482605e7260ff5b92735a6060930c90636050166001ff9060f1855201350493601990ff90825660606060a05202579050405b52f6036091918461f2605b02730260109550ff00602060039016600904815060189f5503612000dd9036520360ffffff5e6082508200600001836060005502ffffff16835074528f6016578aff500b908190929103273250905655e6730101858090ffaa00010081905060a06061610180ff120460409102ff9020601d63500085010041604660633e619480140100828081ff0336576150a3608102ff2004605260ff6090605750605501ff60246060005260ff80600284911601600060910060200a57dd82ff2be90102905bff486f600401160391015760012060ffff0256605b50820181915b60ff83606001000163ff0091ff5bff028257815007ff8e061803b12e159635605b20806060d013618014602060ffff0d829061ace03382ff011f1201008b608183ff60037fff246001ffff5282ff8301906090910020ff81016000001483ff7e50fe628250ff80ff57500061107a54e85b2001505500f46191278250ff604960504081169055006061608761016004fc61d72a19169152340119838050ff81154080ff201560019161520196003da060b65b15ff60825754ff7a5b572082040000c5006052020152e660be018160905002f381ff240001038450607b080380016090906060616060526104ffcc3d03ff63016061ff838061ff00d6016050370200310dff6094616090b600ff6007ff01dba702ff900090506081ffffd80061569001405020bdc6809161558008836012690060cc548056ae0a00526173005060908080025400ff5460a039018290610183ff14f360ff4050dfac06604060a2617a0040600260600160ff0161849283606020012000ff6060ff8220603760c0ff201c50048261ff910062016002907778810168613700ff1501559004ff01520237ff8154da1a92905152508500035260523320010001192dff818915e7f3208700525b00032e3b15019057810001805b003f4014ff5b5b8102c07fffff63400080406020615013605050010bff60900191d0806035f1915b61405000ff81511490076000ff8200ff001f5182606050ff52ffd73e6071012057005703908382ff54012000835204548000280260618660739160376020836000fe5084cc6352506060816052ff5160569090ff9001155a00815a60618102818361605050186001615b03165035699081ff81ff9140605690632b1aff00619015c9dd6060505054606101b66150043d201605505b60815290030001026120c030041238164856ff810a52616160400050576081100054ffff8200765020f6008340800044616060900252578401738033032002ed73108060369080605661365950566e1650b084c940140090c30202098110825be1009073064061ffff60016000b260f19001500161ff5b605b9080506120ff0000575054205b0051ff615657336037ff205b1490f1608181860b7f90335060601660ff11198693140101006022ff01ff04735001ff02153c44edff605082605050500000569052ff500561654061825a7f908190bf80339f72795b60609000605682565450ff508000927f9261ff52ff870116ff8220ff80ffff0e8350604060868291ff8300506118ff610061570e5052ff0015ffff61520081156352006361906106006302610860010390567500549cff6004526016b54060ff5057005011016091802057909382909081004851818184813560815061945601010350ffff61ff01bd605035155416609b02608034800004880052ff5b1563ff02cc155b7300802000506116ff630903b35b000275825b6080565052c6618381039288ff378320616052836bff6057ff5260b5ff14ff6181807387480c0191775752576081ff60835001515a84009090ff006150f616ff60ff8187208001fff2ff51e0019185f601045601c480bf2602606019526000613062506092005b03ff8310ce099001520f00506083230220ff00ff9003015060ff340a1861ff010560818351615b01639060813c8590ff528700605060609090416003715052ff807354607201ff0000ff0d4a506150b15b90f2732350ff57475088000056ff56556073616001ff236060331a0103ff0050ff00601f900361ff1420ff4b888761e45affffff006091006083ff5a5692f3560187035a60508181530c0195ff5b500aff82c2600261498230605bff815b505b03ff8050270a631f0190815092907e730a9020a700825b9050ffc65052", "nonce": "0x41", "storage": {}}, "d94f5374fce5edbc8e2a8697c15331677e6ebf0b": {"balance": "0x405b47e8551987fc", "code": "0x001d00146015001412000018006060000035000a360a6000817ccf0098000200570000190080000a8000606136007e006300350069146157610001008088fd00002690000000001e52610060600060000030c260c0000052016000e437b526e36060000034602760004b600a15021460006139021400192332440061a26000141d8280000301010b815401d683ff83568491514081816182006039039240000a0219955b000383400f55911600800156fb90516bff0914105b810081039081005b011451ffb261606000609009049a0092605220600052ff206015575001005689811060031688810a82ff8826005460ff0000915b81335ad69157030082085690128160605780a1f852029080e165900203526360020490606081029181504001735291616190010061508052ffff5490cb0e739161859280904084165b928060001093ff6002945701f10aff6052ffff20ff4080849201cdff8161820091010060528060007f50ae0060245091501092615104010093520100526c600201804f348160030f84555b6000beffc8ff028252806000006090026060009b6096851501ffff208480ff150250909001908050ff1e60600154606160ff809020ff81801f0057ff00ffff5460019060be84167315505b60011601618850606080ff01609c5055ffff203de6560601526000500003ff610457616110ff810009515bc150500120500301ff81738061608417870f85ff36ff2aa00156b603045690cdc99116605014ff35608052ff019002575282041060205691805bef8300409303c6018761d1ff0000906160bb60200160610352916061619083578401510affd2d991608085a1810a500020598200228160555061016161ffff82909354605504080200608160449081a0ff55500090e061600080906083806c00806061ffff6050ad006050611478576090602060619024021591196100612256600190061c375461151461ea0360f180fc6019001500ff5b92615016605051546161030073206012ff160261ffd68184605400ff01916073609150118400918556db60731fff600200010bff1481600190810a035055ffff601c60cd02015001f16482825204540460031501835b5b86006090ff90001460005650ee1f81400610029c2090150105ffff80600150ffeaf7571402ff60901100506037ff900334605000928360ff5b809052ff5b400320ff67204000ff6060ff5b9104821f6003a9030100ff14ff510401ff9060206052608120ffff04ae1501208482fc505b606001406081510a900090545b902073ff60095090505b6060510060ff16ff81010150ffff925b60a7606060570060005200ff50ff732015ffa30082605b2040600180162085cc33516300800a8b60ffff3d440020606056b51533ff01605b616060909182810a57ffff60a36100ff91ff810104cf5250545a00015081ff52606c55828454ff900090821eb460614000ff57525401575b616050906016605060605b161d0187ff51ff60820f61508154166003900002ff8050155000ff20820081ff87160d913760258454918233a05652602032905b018082f4b560810a800060506112ff56ff80815050576140908161b6816007ff1533d00e0100605001ff016052626060007f1450575100004360ff358156448080605a80fff3ff63006082e81460618351ff526020ff055257521b45406150166082826020159115ff955716103515010356b4900061200350039002ff026120060a20025780800191ff6d906020a30300909b5503018090ff61007f5b0060ff8085325790ff234004ff56bf6157ff80016160305286576060630060ff81ff0b520327b78002f3815b6086e30260738160007a9016ffffff5b400b82513502f300685550da1560205222ff9a00066098ff5b51351503005080ff906000e0039020810aff5060ff88ffee90ff515050810052817cb2000080816050810150c2507f5a5650e460695091605b16ff910337909250b0ee00a2918320600150ff1556235000b557ff561e1601c4565050032390ff16ff6056005d805b51ff50ff202872018301ff012880f3ee94ffffb4036016ffa03531601e50372b61605bb660275b00005f546027ff505b9482ff5b50ff540103206056d9036050", "nonce": "0x41", "storage": {}}, "a94f5374fce5edbc8e2a8697c15331677e6ebf0b": {"balance": "0xf8b9ab29d1ce492e", "code": "0x", "nonce": "0x41", "storage": {}}}, "transaction": {"data": ["0x1963f2008001ff2382a26060005702d2000060001e226081410037f34063635257605757526057007c00531357610060808114f27c0014600000568138000a5700f91437404e5704006057142200000000356000601460356015608441316000600060006100c08b63605a0063010a0030006000de60808002600000606035616319905640022ff5544dff005252405261500401151660605130500004528160601660910040851d70846cff030181ff61ffff8003c900ff158219391fff141481ff6020ff83909000000101010118a781026088601c60f8525b60ff5593840102be60576860ff205115ff81ff000101816084570120ff81ff78572252816060805014ff205483ff906061ffff908260ff500f0a01148115a0605f9081ff875ba5910050ffd48510917c91009152790120015b5102060020918216606304618114605060905b0142611600008534209014017f5103935bff601600200002604034546090601e5250016050ff9161849cad15b52d16ff9001020a555b6050107391010160630190205000610380519280ff559e047f57ff145060018082130124ff5456606809505248ff600592f6491250603461008b6010010181006351d109635080ff6004805702365b556091601c54e028630216ff200214816360ff0085efff7360ff4f8161ff615b508235ff01876001a003160f86906001ff90506056528257820251025757601601865280570a2090ff5290006002355161150a836000001f90ff5b5616505b82600ac961019052f568a8ff5050a095520000e88151ff8181640860520183011690ffc5ff608200010d01009361770116736d1490505581610014685783613812196080200420904200ff4001600002ff60606100570152019020ff606061805455500352150060149101b800b80056050a606040360a60925200910100018003339230966050006000016063506091a080608204906095505b526061000402618402ff73810a56608166ff5001048390604616565a0201605b0061640584f3ff001501926014050a2056611283001855506020006001200a630057610004ff010055000d60016116011f500a140a15010101005252605220600182a080008100ff0a605090ffb4028138d6ff5500ee8f82365002387306cbe86081045b90016190f6610001525481605561a0409215915085911681025115ff910190500095165660ff82035220ff6000805b900051ff20045250811fb363f19763010001ff6800166106a081d5606085ffff9060608101ff835f1184353507559301a0026090ff016000616303017300789435160181200a815720000100006150515701608461805b005b55600250625090826050615760610056ff50160080005740fc82da011150e0a000525480ed02a38060d191ff918151ff90208116528260542d018b5f616091810390028101740401610320025150d74360605b52ff60ff6157b5018250ff80578280ff0151ff1407005055ff9060806051ff050061e582600354726161908090609101016160560002da578100604060a0609073ffff5192ff806060191214638102009182ff03000c50805582546050851f6963606019ff0181819061e45b404f5000ffffff8740141d00cc165bff8355240281616040ff6090205000b50a00ff91006078a0930180010208525060e9506016073787e45a600054ff1661731d0009208288f1900090605601e48200d239809119ff114a8837568060f256ff50b6906081500122f261a33161ffff5a578790508381915a00ff00005b8d83560895908057900350ff029bdd906050ffee01d211e0566056326090d9ff01619060015a195632ed565aa9392282a2505b50bb60b060"], "gasLimit": ["0x2a4f65", "3000000"], "gasPrice": "0x05", "nonce": "0x41", "secretKey": "0x45a915e4d060149eb4365960e6a7a45f334393093061116b197e3240065ff2d8", "to": "0x1000000000000000000000000000000000000000", "value": ["0x2c18f078", "0"]}}}
```

### PR DESCRIPTION
**Pull request by sorpaas**
Fixes #9408

* When state root mismatch, prints the actual gas used instead of total gas.
* Output full hash of state root hashes in error message.
* Change `std_json` informant to have two sinks, one for traces (which default to stderr), and another for test results (which defaults to stdout).

### CODE REVIEW

File: evmbin/src/display/std_json.rs [hunk 1]
```diff
@@ -28,44 +28,60 @@ use info as vm;
...
+	}
+
+	fn default() -> Self {
+		io::stderr()
+	}
 }
 
 /// JSON formatting informant.
-pub struct Informant<T: Writer = io::Stdout> {
+pub struct Informant<Trace: Writer = io::Stderr, Out: Writer = io::Stdout> {
```
Comment (ordian) [inline evmbin/src/display/std_json.rs]: Should we remove trait bound from the struct? (see #9055)

File: evmbin/src/display/std_json.rs [hunk 2]
```diff
@@ -28,44 +28,60 @@ use info as vm;
...
+impl<Trace: Writer, Out: Writer> Informant<Trace, Out> {
+	pub fn new(trace_sink: Trace, out_sink: Out) -> Self {
 		Informant {
 			code: Default::default(),
 			instruction: Default::default(),
 			depth: Default::default(),
 			stack: Default::default(),
 			storage: Default::default(),
-			sink,
+			trace_sink, out_sink
```
Comment (ordian) [inline evmbin/src/display/std_json.rs]: Why not
```rust
Informant {
	trace_sink,
	out_sink,
	..Default::default(),
}
```

Comment (sorpaas) [reply evmbin/src/display/std_json.rs]: Looks like this doesn't work.

```
the trait `std::default::Default` is not implemented for `display::std_json::Informant<Trace, Out>`
```
