### PR TITLE
Fix fork choice

### LINKED ISSUE #10085: Node is failing to sync with error "Error: Error(Engine(RequiresClient)"
- **Parity Ethereum version**: tried 2.2.5 and 2.2.1 
- **Operating system**: Ubuntu 16/18
- **Installation**: downloaded binary
- **Fully synchronized**: no and yes
- **Network**: POA xDAI
- **Restarted**: both
Error log:
```
2018-12-19 13:31:46  Stage 3 block verification failed for #1210413 (0xc2a1…9c29)
Error: Error(Engine(RequiresClient), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
2018-12-19 13:31:46  
Bad block detected: Error(Engine(RequiresClient), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
RLP: f90249f90244a015bf167c5b4c07587408ce07860c6a8a6f4ea098c2457f86042575e4073db456a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347946dc0c0be4c8b2dfe750156dc7d59faabfb5b923da0518feb50424fef5033af4fd2d11281e7919218c2538d45db7433191e3c0347d0a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b901000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000090fffffffffffffffffffffffffffffffd8312782d8398968080845c1a1e0c9fde830202018f5061726974792d457468657265756d86312e33302e31826c6984126b9f9cb8416432efb986cffdd90973796712f64819aa5daa07ecd21a40284c6a82f1dd7fe64e031a733e95c40e6dae2f9d52c0b56c4f380b189ce17409fe79066d0cf4109b00c0c0
Header: Header { parent_hash: 0x15bf167c5b4c07587408ce07860c6a8a6f4ea098c2457f86042575e4073db456, timestamp: 1545215500, number: 1210413, author: 0x6dc0c0be4c8b2dfe750156dc7d59faabfb5b923d, transactions_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, uncles_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, extra_data: [222, 131, 2, 2, 1, 143, 80, 97, 114, 105, 116, 121, 45, 69, 116, 104, 101, 114, 101, 117, 109, 134, 49, 46, 51, 48, 46, 49, 130, 108, 105], state_root: 0x518feb50424fef5033af4fd2d11281e7919218c2538d45db7433191e3c0347d0, receipts_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, log_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, gas_used: 0, gas_limit: 10000000, difficulty: 340282366920938463463374607431768211453, seal: [[132, 18, 107, 159, 156], [184, 65, 100, 50, 239, 185, 134, 207, 253, 217, 9, 115, 121, 103, 18, 246, 72, 25, 170, 93, 170, 7, 236, 210, 26, 64, 40, 76, 106, 130, 241, 221, 127, 230, 78, 3, 26, 115, 62, 149, 196, 14, 109, 174, 47, 157, 82, 192, 181, 108, 79, 56, 11, 24, 156, 225, 116, 9, 254, 121, 6, 109, 12, 244, 16, 155, 0]], hash: Some(0xc2a1a685d2cedd5f3c69826bfb7a8210213dd58e177dd438512baaa717cb9c29) }
Uncles: 
Transactions:


```

We have launched a number of validator nodes at xDAI network (statistics at https://dai-netstat.poa.network) at AWS that works pretty fine. After that we have tried to launch one of the nodes via the same way, but at the local infrastructure (Protofire Validator). Node is hided behind the NAT, and 30303 port were made public. It worked fine for some time and then errors started to occur (see logs above). We've launched a full resync, and it helped, but for a short period of time only.
We've decided, that the roots of that issue might lie in a fact that Ubuntu 18 were used. So we launched an Ubuntu 16, but it didn't help.
Can you help us solving the issue?

### PR DESCRIPTION
**Pull request by ngotchac**
Fixes #10085 

It seems that `is_from_route_finalized` was computed for the parent's block finalization at each iteration in `fn tree_route`. Thus if a fork happened, and the common ancestor was finalized, the `from` branch would be marked as `finalized` although it wasn't, and the switch to the better branch would never happened.

### CODE REVIEW

**Comment by dvdplm** [comment]
The test failure here is fixable by a rebase.

**Comment by ngotchac** [comment]
@tomusdrw I added tests for `tree_route` as you described, but didn't modify the behavior you described on test case 4. I'm actually not quite sure where this could occur, so I don't know if we should modify it or not.

File: ethcore/blockchain/src/generator.rs [hunk 1]
```diff
@@ -136,6 +138,29 @@ impl BlockBuilder {
 		})
 	}
 
+	/// Add a block with randomly generated transactions.
+	#[inline]
```
Comment (dvdplm) [inline ethcore/blockchain/src/generator.rs]: This is a test helper yes? Is it performance sensitive?

File: ethcore/blockchain/src/generator.rs [hunk 2]
```diff
@@ -166,11 +191,19 @@ impl BlockBuilder {
 			let mut block = Block::default();
 			let metadata = get_metadata();
 			let block_number = parent_number + 1;
+			let transactions = metadata.transactions;
+			let transactions_root = ordered_trie_root(transactions.iter().map(|tx| {
```
Comment (dvdplm) [inline ethcore/blockchain/src/generator.rs]: You sure you need to loop over all txs and encode them like this, and why as a stream and not `rlp::encode`? Honest question, I really don't know!

Comment (debris) [reply ethcore/blockchain/src/generator.rs]: yeh, `.map(rlp::encode)` produces the same result and is shorter

File: ethcore/blockchain/src/blockchain.rs [hunk 3]
```diff
@@ -2503,4 +2503,74 @@ mod tests {
...
+			assert!(!bc.tree_route(b2_hash, a3_hash).unwrap().is_from_route_finalized);
+		}
+
+		// Case 3: no-fork, with a finalized block
+		{
+			let (db, bc) = bootstrap_chain(vec![&a, &a1, &a2]);
+			assert_eq!(bc.best_block_hash(), a2_hash);
+
+			mark_finalized(a1_hash, &db, &bc);
+			assert!(!bc.tree_route(a1_hash, a2_hash).unwrap().is_from_route_finalized);
```
Comment (tomusdrw) [inline ethcore/blockchain/src/blockchain.rs]: Can we document this counter intuitive behavior in the function docs? A small `NOTE` would suffice, that `is_from_route_finalized` works only if `from` and `to` are on different forks (i.e. have common ancestor or one is not an ancestor of the other)

File: ethcore/blockchain/src/generator.rs (hunk 1 above)
Comment (ngotchac) [reply ethcore/blockchain/src/generator.rs]: Yeah I think it's only used for tests. I just followed the structure of the other similar methods, so I'm not sure whether `inline` is needed here.

File: ethcore/blockchain/src/blockchain.rs (hunk 3 above)
Comment (ngotchac) [reply ethcore/blockchain/src/blockchain.rs]: Yep, I added a comment to the `tree_route` method.

File: Cargo.lock [hunk 4]
```diff
@@ -55,18 +55,26 @@ dependencies = [
 
 [[package]]
 name = "aho-corasick"
-version = "0.6.8"
+version = "0.6.10"
```
Comment (ordian) [inline Cargo.lock]: did you run `cargo update`? :)
it would make backporting harder, so please revert

File: ethcore/blockchain/Cargo.toml [hunk 5]
```diff
@@ -13,21 +13,23 @@ blooms-db = { path = "../../util/blooms-db" }
...
 ethcore-db = { path = "../db" }
 ethereum-types = "0.6.0"
+keccak-hash = "0.2.0"
 parity-util-mem = "0.1"
 itertools = "0.5"
 kvdb = "0.1"
 log = "0.4"
 parity-bytes = "0.1"
 parking_lot = "0.8"
+rand = "0.6"
```
Comment (ordian) [inline ethcore/blockchain/Cargo.toml]: should be it be a dev dep?

Comment (ngotchac) [reply ethcore/blockchain/Cargo.toml]: No, actually the `generator.rs` module is not for tests only

File: Cargo.lock (hunk 4 above)
Comment (ngotchac) [reply Cargo.lock]: Hm, I just deleted the lock file and re-built the project...

Comment (debris) [reply Cargo.lock]: instead of deleting, can you checkout `Cargo.lock` from master and build it with it?

```
git checkout master Cargo.lock
cargo check
```

Comment (ngotchac) [reply Cargo.lock]: Yeah sure, sorry about that. Done.

**Comment by phahulin** [comment]
Is this included in any of the already released versions (the last one atm is 2.5.6)? If not yet, which version is it scheduled to be included into?

**Comment by joshua-mir** [comment]
@phahulin it was included in 2.6.0 (beta) so it is available on the 2.6 branch releases - I'm not sure if it was backported to stable at any point as well though...
